/**
 * ISO 3166-1 alpha-3 country code mapping
 * Maps alpha-2 -> alpha-3 codes
 */
export const COUNTRY_ALPHA3_MAP: Record<string, string> = {
  ad: 'AND',
  ae: 'ARE',
  af: 'AFG',
  ag: 'ATG',
  ai: 'AIA',
  al: 'ALB',
  am: 'ARM',
  ao: 'AGO',
  ar: 'ARG',
  as: 'ASM',
  at: 'AUT',
  au: 'AUS',
  aw: 'ABW',
  az: 'AZE',
  ba: 'BIH',
  bb: 'BRB',
  bd: 'BGD',
  be: 'BEL',
  bf: 'BFA',
  bg: 'BGR',
  bh: 'BHR',
  bi: 'BDI',
  bj: 'BEN',
  bm: 'BMU',
  bn: 'BRN',
  bo: 'BOL',
  br: 'BRA',
  bs: 'BHS',
  bt: 'BTN',
  bw: 'BWA',
  by: 'BLR',
  bz: 'BLZ',
  ca: 'CAN',
  cd: 'COD',
  cf: 'CAF',
  cg: 'COG',
  ch: 'CHE',
  ci: 'CIV',
  cl: 'CHL',
  cm: 'CMR',
  cn: 'CHN',
  co: 'COL',
  cr: 'CRI',
  cu: 'CUB',
  cv: 'CPV',
  cy: 'CYP',
  cz: 'CZE',
  de: 'DEU',
  dj: 'DJI',
  dk: 'DNK',
  dm: 'DMA',
  do: 'DOM',
  dz: 'DZA',
  ec: 'ECU',
  ee: 'EST',
  eg: 'EGY',
  er: 'ERI',
  es: 'ESP',
  et: 'ETH',
  fi: 'FIN',
  fj: 'FJI',
  fm: 'FSM',
  fr: 'FRA',
  ga: 'GAB',
  gb: 'GBR',
  gd: 'GRD',
  ge: 'GEO',
  gh: 'GHA',
  gm: 'GMB',
  gn: 'GIN',
  gq: 'GNQ',
  gr: 'GRC',
  gt: 'GTM',
  gw: 'GNB',
  gy: 'GUY',
  hk: 'HKG',
  hn: 'HND',
  hr: 'HRV',
  ht: 'HTI',
  hu: 'HUN',
  id: 'IDN',
  ie: 'IRL',
  il: 'ISR',
  in: 'IND',
  iq: 'IRQ',
  ir: 'IRN',
  is: 'ISL',
  it: 'ITA',
  jm: 'JAM',
  jo: 'JOR',
  jp: 'JPN',
  ke: 'KEN',
  kg: 'KGZ',
  kh: 'KHM',
  ki: 'KIR',
  km: 'COM',
  kn: 'KNA',
  kp: 'PRK',
  kr: 'KOR',
  kw: 'KWT',
  ky: 'CYM',
  kz: 'KAZ',
  la: 'LAO',
  lb: 'LBN',
  lc: 'LCA',
  li: 'LIE',
  lk: 'LKA',
  lr: 'LBR',
  ls: 'LSO',
  lt: 'LTU',
  lu: 'LUX',
  lv: 'LVA',
  ly: 'LBY',
  ma: 'MAR',
  mc: 'MCO',
  md: 'MDA',
  me: 'MNE',
  mg: 'MDG',
  mh: 'MHL',
  mk: 'MKD',
  ml: 'MLI',
  mm: 'MMR',
  mn: 'MNG',
  mo: 'MAC',
  mr: 'MRT',
  mt: 'MLT',
  mu: 'MUS',
  mv: 'MDV',
  mw: 'MWI',
  mx: 'MEX',
  my: 'MYS',
  mz: 'MOZ',
  na: 'NAM',
  ne: 'NER',
  ng: 'NGA',
  ni: 'NIC',
  nl: 'NLD',
  no: 'NOR',
  np: 'NPL',
  nr: 'NRU',
  nz: 'NZL',
  om: 'OMN',
  pa: 'PAN',
  pe: 'PER',
  pg: 'PNG',
  ph: 'PHL',
  pk: 'PAK',
  pl: 'POL',
  pt: 'PRT',
  pw: 'PLW',
  py: 'PRY',
  qa: 'QAT',
  ro: 'ROU',
  rs: 'SRB',
  ru: 'RUS',
  rw: 'RWA',
  sa: 'SAU',
  sb: 'SLB',
  sc: 'SYC',
  sd: 'SDN',
  se: 'SWE',
  sg: 'SGP',
  si: 'SVN',
  sk: 'SVK',
  sl: 'SLE',
  sm: 'SMR',
  sn: 'SEN',
  so: 'SOM',
  sr: 'SUR',
  ss: 'SSD',
  st: 'STP',
  sv: 'SLV',
  sy: 'SYR',
  sz: 'SWZ',
  td: 'TCD',
  tg: 'TGO',
  th: 'THA',
  tj: 'TJK',
  tl: 'TLS',
  tm: 'TKM',
  tn: 'TUN',
  to: 'TON',
  tr: 'TUR',
  tt: 'TTO',
  tv: 'TUV',
  tw: 'TWN',
  tz: 'TZA',
  ua: 'UKR',
  ug: 'UGA',
  us: 'USA',
  uy: 'URY',
  uz: 'UZB',
  ve: 'VEN',
  vn: 'VNM',
  vu: 'VUT',
  ws: 'WSM',
  xk: 'XKX',
  ye: 'YEM',
  za: 'ZAF',
  zm: 'ZMB',
  zw: 'ZWE',
};

/**
 * Reverse map: alpha-3 -> alpha-2
 */
export const COUNTRY_ALPHA3_REVERSE: Record<string, string> = Object.fromEntries(
  Object.entries(COUNTRY_ALPHA3_MAP).map(([a2, a3]) => [a3, a2])
);

/**
 * Set of valid alpha-3 codes for quick lookup
 */
export const COUNTRY_ALPHA3_SET = new Set(Object.values(COUNTRY_ALPHA3_MAP));

/**
 * Get alpha-3 code from alpha-2 code
 */
export const getAlpha3FromAlpha2 = (alpha2: string): string | undefined => {
  return COUNTRY_ALPHA3_MAP[alpha2.toLowerCase()];
};

/**
 * Get alpha-2 code from alpha-3 code
 */
export const getAlpha2FromAlpha3 = (alpha3: string): string | undefined => {
  return COUNTRY_ALPHA3_REVERSE[alpha3.toUpperCase()];
};
