/**
 * ISO 3166-1 alpha-2 country data
 * Contains country code, English name, and native name
 */
export interface Country {
  code: string; // ISO 3166-1 alpha-2 (lowercase)
  name: string; // English name
  native: string; // Native name
}

/**
 * Get flag image URL from flagcdn.com
 * flagcdn.com only supports specific widths: 20, 40, 80, 160, 320, 640
 * @param countryCode ISO 3166-1 alpha-2 code (case insensitive)
 * @param displaySize Display size in pixels - will be mapped to nearest supported CDN width
 */
const SUPPORTED_WIDTHS = [20, 40, 80, 160, 320, 640];

export const getFlagUrl = (countryCode: string, displaySize = 20): string => {
  // Pick the smallest supported width that is >= displaySize for crisp rendering
  const cdnWidth = SUPPORTED_WIDTHS.find((w) => w >= displaySize) || 640;
  return `https://flagcdn.com/w${cdnWidth}/${countryCode.toLowerCase()}.png`;
};

/**
 * Full list of countries with ISO 3166-1 alpha-2 codes
 */
export const COUNTRIES: Country[] = [
  { code: 'ad', name: 'Andorra', native: 'Andorra' },
  {
    code: 'ae',
    name: 'United Arab Emirates',
    native: 'الإمارات العربية المتحدة',
  },
  { code: 'af', name: 'Afghanistan', native: 'افغانستان' },
  { code: 'ag', name: 'Antigua and Barbuda', native: 'Antigua and Barbuda' },
  { code: 'ai', name: 'Anguilla', native: 'Anguilla' },
  { code: 'al', name: 'Albania', native: 'Shqipëria' },
  { code: 'am', name: 'Armenia', native: 'Հայաստան' },
  { code: 'ao', name: 'Angola', native: 'Angola' },
  { code: 'ar', name: 'Argentina', native: 'Argentina' },
  { code: 'as', name: 'American Samoa', native: 'American Samoa' },
  { code: 'at', name: 'Austria', native: 'Österreich' },
  { code: 'au', name: 'Australia', native: 'Australia' },
  { code: 'aw', name: 'Aruba', native: 'Aruba' },
  { code: 'az', name: 'Azerbaijan', native: 'Azərbaycan' },
  { code: 'ba', name: 'Bosnia and Herzegovina', native: 'Bosna i Hercegovina' },
  { code: 'bb', name: 'Barbados', native: 'Barbados' },
  { code: 'bd', name: 'Bangladesh', native: 'বাংলাদেশ' },
  { code: 'be', name: 'Belgium', native: 'België' },
  { code: 'bf', name: 'Burkina Faso', native: 'Burkina Faso' },
  { code: 'bg', name: 'Bulgaria', native: 'България' },
  { code: 'bh', name: 'Bahrain', native: 'البحرين' },
  { code: 'bi', name: 'Burundi', native: 'Burundi' },
  { code: 'bj', name: 'Benin', native: 'Bénin' },
  { code: 'bm', name: 'Bermuda', native: 'Bermuda' },
  { code: 'bn', name: 'Brunei', native: 'Brunei' },
  { code: 'bo', name: 'Bolivia', native: 'Bolivia' },
  { code: 'br', name: 'Brazil', native: 'Brasil' },
  { code: 'bs', name: 'Bahamas', native: 'Bahamas' },
  { code: 'bt', name: 'Bhutan', native: 'འབྲུག' },
  { code: 'bw', name: 'Botswana', native: 'Botswana' },
  { code: 'by', name: 'Belarus', native: 'Беларусь' },
  { code: 'bz', name: 'Belize', native: 'Belize' },
  { code: 'ca', name: 'Canada', native: 'Canada' },
  { code: 'cd', name: 'DR Congo', native: 'République démocratique du Congo' },
  {
    code: 'cf',
    name: 'Central African Republic',
    native: 'République centrafricaine',
  },
  { code: 'cg', name: 'Republic of the Congo', native: 'République du Congo' },
  { code: 'ch', name: 'Switzerland', native: 'Schweiz' },
  { code: 'ci', name: "Côte d'Ivoire", native: "Côte d'Ivoire" },
  { code: 'cl', name: 'Chile', native: 'Chile' },
  { code: 'cm', name: 'Cameroon', native: 'Cameroun' },
  { code: 'cn', name: 'China', native: '中国' },
  { code: 'co', name: 'Colombia', native: 'Colombia' },
  { code: 'cr', name: 'Costa Rica', native: 'Costa Rica' },
  { code: 'cu', name: 'Cuba', native: 'Cuba' },
  { code: 'cv', name: 'Cape Verde', native: 'Cabo Verde' },
  { code: 'cy', name: 'Cyprus', native: 'Κύπρος' },
  { code: 'cz', name: 'Czech Republic', native: 'Česká republika' },
  { code: 'de', name: 'Germany', native: 'Deutschland' },
  { code: 'dj', name: 'Djibouti', native: 'Djibouti' },
  { code: 'dk', name: 'Denmark', native: 'Danmark' },
  { code: 'dm', name: 'Dominica', native: 'Dominica' },
  { code: 'do', name: 'Dominican Republic', native: 'República Dominicana' },
  { code: 'dz', name: 'Algeria', native: 'الجزائر' },
  { code: 'ec', name: 'Ecuador', native: 'Ecuador' },
  { code: 'ee', name: 'Estonia', native: 'Eesti' },
  { code: 'eg', name: 'Egypt', native: 'مصر' },
  { code: 'er', name: 'Eritrea', native: 'ኤርትራ' },
  { code: 'es', name: 'Spain', native: 'España' },
  { code: 'et', name: 'Ethiopia', native: 'ኢትዮጵያ' },
  { code: 'fi', name: 'Finland', native: 'Suomi' },
  { code: 'fj', name: 'Fiji', native: 'Fiji' },
  { code: 'fm', name: 'Micronesia', native: 'Micronesia' },
  { code: 'fr', name: 'France', native: 'France' },
  { code: 'ga', name: 'Gabon', native: 'Gabon' },
  { code: 'gb', name: 'United Kingdom', native: 'United Kingdom' },
  { code: 'gd', name: 'Grenada', native: 'Grenada' },
  { code: 'ge', name: 'Georgia', native: 'საქართველო' },
  { code: 'gh', name: 'Ghana', native: 'Ghana' },
  { code: 'gm', name: 'Gambia', native: 'Gambia' },
  { code: 'gn', name: 'Guinea', native: 'Guinée' },
  { code: 'gq', name: 'Equatorial Guinea', native: 'Guinea Ecuatorial' },
  { code: 'gr', name: 'Greece', native: 'Ελλάδα' },
  { code: 'gt', name: 'Guatemala', native: 'Guatemala' },
  { code: 'gw', name: 'Guinea-Bissau', native: 'Guiné-Bissau' },
  { code: 'gy', name: 'Guyana', native: 'Guyana' },
  { code: 'hk', name: 'Hong Kong', native: '香港' },
  { code: 'hn', name: 'Honduras', native: 'Honduras' },
  { code: 'hr', name: 'Croatia', native: 'Hrvatska' },
  { code: 'ht', name: 'Haiti', native: 'Haïti' },
  { code: 'hu', name: 'Hungary', native: 'Magyarország' },
  { code: 'id', name: 'Indonesia', native: 'Indonesia' },
  { code: 'ie', name: 'Ireland', native: 'Éire' },
  { code: 'il', name: 'Israel', native: 'ישראל' },
  { code: 'in', name: 'India', native: 'भारत' },
  { code: 'iq', name: 'Iraq', native: 'العراق' },
  { code: 'ir', name: 'Iran', native: 'ایران' },
  { code: 'is', name: 'Iceland', native: 'Ísland' },
  { code: 'it', name: 'Italy', native: 'Italia' },
  { code: 'jm', name: 'Jamaica', native: 'Jamaica' },
  { code: 'jo', name: 'Jordan', native: 'الأردن' },
  { code: 'jp', name: 'Japan', native: '日本' },
  { code: 'ke', name: 'Kenya', native: 'Kenya' },
  { code: 'kg', name: 'Kyrgyzstan', native: 'Кыргызстан' },
  { code: 'kh', name: 'Cambodia', native: 'កម្ពុជា' },
  { code: 'ki', name: 'Kiribati', native: 'Kiribati' },
  { code: 'km', name: 'Comoros', native: 'جزر القمر' },
  {
    code: 'kn',
    name: 'Saint Kitts and Nevis',
    native: 'Saint Kitts and Nevis',
  },
  { code: 'kp', name: 'North Korea', native: '조선민주주의인민공화국' },
  { code: 'kr', name: 'South Korea', native: '대한민국' },
  { code: 'kw', name: 'Kuwait', native: 'الكويت' },
  { code: 'ky', name: 'Cayman Islands', native: 'Cayman Islands' },
  { code: 'kz', name: 'Kazakhstan', native: 'Қазақстан' },
  { code: 'la', name: 'Laos', native: 'ລາວ' },
  { code: 'lb', name: 'Lebanon', native: 'لبنان' },
  { code: 'lc', name: 'Saint Lucia', native: 'Saint Lucia' },
  { code: 'li', name: 'Liechtenstein', native: 'Liechtenstein' },
  { code: 'lk', name: 'Sri Lanka', native: 'ශ්‍රී ලංකාව' },
  { code: 'lr', name: 'Liberia', native: 'Liberia' },
  { code: 'ls', name: 'Lesotho', native: 'Lesotho' },
  { code: 'lt', name: 'Lithuania', native: 'Lietuva' },
  { code: 'lu', name: 'Luxembourg', native: 'Lëtzebuerg' },
  { code: 'lv', name: 'Latvia', native: 'Latvija' },
  { code: 'ly', name: 'Libya', native: 'ليبيا' },
  { code: 'ma', name: 'Morocco', native: 'المغرب' },
  { code: 'mc', name: 'Monaco', native: 'Monaco' },
  { code: 'md', name: 'Moldova', native: 'Moldova' },
  { code: 'me', name: 'Montenegro', native: 'Crna Gora' },
  { code: 'mg', name: 'Madagascar', native: 'Madagasikara' },
  { code: 'mh', name: 'Marshall Islands', native: 'Marshall Islands' },
  { code: 'mk', name: 'North Macedonia', native: 'Северна Македонија' },
  { code: 'ml', name: 'Mali', native: 'Mali' },
  { code: 'mm', name: 'Myanmar', native: 'မြန်မာ' },
  { code: 'mn', name: 'Mongolia', native: 'Монгол' },
  { code: 'mo', name: 'Macau', native: '澳門' },
  { code: 'mr', name: 'Mauritania', native: 'موريتانيا' },
  { code: 'mt', name: 'Malta', native: 'Malta' },
  { code: 'mu', name: 'Mauritius', native: 'Maurice' },
  { code: 'mv', name: 'Maldives', native: 'Maldives' },
  { code: 'mw', name: 'Malawi', native: 'Malawi' },
  { code: 'mx', name: 'Mexico', native: 'México' },
  { code: 'my', name: 'Malaysia', native: 'Malaysia' },
  { code: 'mz', name: 'Mozambique', native: 'Moçambique' },
  { code: 'na', name: 'Namibia', native: 'Namibia' },
  { code: 'ne', name: 'Niger', native: 'Niger' },
  { code: 'ng', name: 'Nigeria', native: 'Nigeria' },
  { code: 'ni', name: 'Nicaragua', native: 'Nicaragua' },
  { code: 'nl', name: 'Netherlands', native: 'Nederland' },
  { code: 'no', name: 'Norway', native: 'Norge' },
  { code: 'np', name: 'Nepal', native: 'नेपाल' },
  { code: 'nr', name: 'Nauru', native: 'Nauru' },
  { code: 'nz', name: 'New Zealand', native: 'New Zealand' },
  { code: 'om', name: 'Oman', native: 'عمان' },
  { code: 'pa', name: 'Panama', native: 'Panamá' },
  { code: 'pe', name: 'Peru', native: 'Perú' },
  { code: 'pg', name: 'Papua New Guinea', native: 'Papua New Guinea' },
  { code: 'ph', name: 'Philippines', native: 'Pilipinas' },
  { code: 'pk', name: 'Pakistan', native: 'پاکستان' },
  { code: 'pl', name: 'Poland', native: 'Polska' },
  { code: 'pt', name: 'Portugal', native: 'Portugal' },
  { code: 'pw', name: 'Palau', native: 'Palau' },
  { code: 'py', name: 'Paraguay', native: 'Paraguay' },
  { code: 'qa', name: 'Qatar', native: 'قطر' },
  { code: 'ro', name: 'Romania', native: 'România' },
  { code: 'rs', name: 'Serbia', native: 'Србија' },
  { code: 'ru', name: 'Russia', native: 'Россия' },
  { code: 'rw', name: 'Rwanda', native: 'Rwanda' },
  { code: 'sa', name: 'Saudi Arabia', native: 'السعودية' },
  { code: 'sb', name: 'Solomon Islands', native: 'Solomon Islands' },
  { code: 'sc', name: 'Seychelles', native: 'Seychelles' },
  { code: 'sd', name: 'Sudan', native: 'السودان' },
  { code: 'se', name: 'Sweden', native: 'Sverige' },
  { code: 'sg', name: 'Singapore', native: 'Singapore' },
  { code: 'si', name: 'Slovenia', native: 'Slovenija' },
  { code: 'sk', name: 'Slovakia', native: 'Slovensko' },
  { code: 'sl', name: 'Sierra Leone', native: 'Sierra Leone' },
  { code: 'sm', name: 'San Marino', native: 'San Marino' },
  { code: 'sn', name: 'Senegal', native: 'Sénégal' },
  { code: 'so', name: 'Somalia', native: 'Soomaaliya' },
  { code: 'sr', name: 'Suriname', native: 'Suriname' },
  { code: 'ss', name: 'South Sudan', native: 'South Sudan' },
  { code: 'st', name: 'São Tomé and Príncipe', native: 'São Tomé e Príncipe' },
  { code: 'sv', name: 'El Salvador', native: 'El Salvador' },
  { code: 'sy', name: 'Syria', native: 'سوريا' },
  { code: 'sz', name: 'Eswatini', native: 'Eswatini' },
  { code: 'td', name: 'Chad', native: 'Tchad' },
  { code: 'tg', name: 'Togo', native: 'Togo' },
  { code: 'th', name: 'Thailand', native: 'ประเทศไทย' },
  { code: 'tj', name: 'Tajikistan', native: 'Тоҷикистон' },
  { code: 'tl', name: 'Timor-Leste', native: 'Timor-Leste' },
  { code: 'tm', name: 'Turkmenistan', native: 'Türkmenistan' },
  { code: 'tn', name: 'Tunisia', native: 'تونس' },
  { code: 'to', name: 'Tonga', native: 'Tonga' },
  { code: 'tr', name: 'Turkey', native: 'Türkiye' },
  { code: 'tt', name: 'Trinidad and Tobago', native: 'Trinidad and Tobago' },
  { code: 'tv', name: 'Tuvalu', native: 'Tuvalu' },
  { code: 'tw', name: 'Taiwan', native: '臺灣' },
  { code: 'tz', name: 'Tanzania', native: 'Tanzania' },
  { code: 'ua', name: 'Ukraine', native: 'Україна' },
  { code: 'ug', name: 'Uganda', native: 'Uganda' },
  { code: 'us', name: 'United States', native: 'United States' },
  { code: 'uy', name: 'Uruguay', native: 'Uruguay' },
  { code: 'uz', name: 'Uzbekistan', native: 'Oʻzbekiston' },
  { code: 've', name: 'Venezuela', native: 'Venezuela' },
  { code: 'vn', name: 'Vietnam', native: 'Việt Nam' },
  { code: 'vu', name: 'Vanuatu', native: 'Vanuatu' },
  { code: 'ws', name: 'Samoa', native: 'Samoa' },
  { code: 'xk', name: 'Kosovo', native: 'Kosovë' },
  { code: 'ye', name: 'Yemen', native: 'اليمن' },
  { code: 'za', name: 'South Africa', native: 'South Africa' },
  { code: 'zm', name: 'Zambia', native: 'Zambia' },
  { code: 'zw', name: 'Zimbabwe', native: 'Zimbabwe' },
];

/**
 * Lookup a country by code
 */
export const getCountryByCode = (code: string): Country | undefined => {
  return COUNTRIES.find((c) => c.code === code.toLowerCase());
};

/**
 * Get display label for a country code: "🇰🇷 South Korea (KR)"
 */
export const getCountryLabel = (code: string): string => {
  const country = getCountryByCode(code);
  if (!country) return code.toUpperCase();
  return `${country.name} (${code.toUpperCase()})`;
};
