supportedArchitectures:
  os: ["win32", "linux"]
  cpu: ["x64"]
  libc: ["glibc", "musl"]

nodeLinker: node-modules

# Force install optional dependencies for all platforms
enableImmutableInstalls: false
