enableImmutableInstalls: false

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - x64
  libc:
    - glibc
    - musl
  os:
    - win32
    - linux

yarnPath: .yarn/releases/yarn-4.13.0.cjs
