/**
 * RBAC Permission Constants
 *
 * Single source of truth for all permission definitions.
 * Used by both frontend and backend.
 *
 * Format: resource:action
 * Wildcard: *:* (all), resource:* (all actions), *:read (all resources)
 */

// ==================== Actions ====================

export const ACTIONS = {
  CREATE: 'create',
  READ: 'read',
  UPDATE: 'update',
  DELETE: 'delete',
  ACCESS: 'access',
  APPROVE: 'approve',
  SKIP: 'skip',
} as const;

export type Action = (typeof ACTIONS)[keyof typeof ACTIONS];

// ==================== Scopes ====================

export const SCOPES = {
  SYSTEM: 'system',
  ORG: 'org',
  PROJECT: 'project',
  ENV: 'env',
} as const;

export type Scope = (typeof SCOPES)[keyof typeof SCOPES];

// ==================== Resources ====================

export const RESOURCES = {
  // System level
  ORGANISATIONS: 'organisations',
  SYSTEM_CONFIG: 'system_config',
  SYSTEM_MONITORING: 'system_monitoring',

  // Org level
  USERS: 'users',
  GROUPS: 'groups',
  ROLES: 'roles',
  INVITATIONS: 'invitations',
  PROJECTS: 'projects',
  AUDIT_LOGS: 'audit_logs',
  SYSTEM_SETTINGS: 'system_settings',
  ADMIN_TOKENS: 'admin_tokens',
  IP_WHITELIST: 'ip_whitelist',
  ACCOUNT_WHITELIST: 'account_whitelist',
  INTEGRATIONS: 'integrations',
  TRANSLATION: 'translation',
  CONSOLE: 'console',
  CHAT: 'chat',
  MONITORING: 'monitoring',
  OPEN_API: 'open_api',
  SCHEDULER: 'scheduler',
  EVENT_LENS: 'event_lens',
  CRASH_EVENTS: 'crash_events',
  REALTIME_EVENTS: 'realtime_events',

  // Project level
  FEATURES: 'features',
  SEGMENTS: 'segments',
  CONTEXT_FIELDS: 'context_fields',
  RELEASE_FLOWS: 'release_flows',
  TAGS: 'tags',
  PLANNING_DATA: 'planning_data',
  SERVICE_ACCOUNTS: 'service_accounts',
  SIGNAL_ENDPOINTS: 'signal_endpoints',
  ACTIONS: 'actions',
  DATA: 'data',
  UNKNOWN_FLAGS: 'unknown_flags',
  IMPACT_METRICS: 'impact_metrics',

  // Env level
  ENVIRONMENTS: 'environments',
  ENV_FEATURES: 'env_features',
  CHANGE_REQUESTS: 'change_requests',
  ENV_KEYS: 'env_keys',
  CLIENT_VERSIONS: 'client_versions',
  GAME_WORLDS: 'game_worlds',
  MAINTENANCE: 'maintenance',
  MAINTENANCE_TEMPLATES: 'maintenance_templates',
  SERVICE_NOTICES: 'service_notices',
  BANNERS: 'banners',
  COUPONS: 'coupons',
  COUPON_SETTINGS: 'coupon_settings',
  SURVEYS: 'surveys',
  STORE_PRODUCTS: 'store_products',
  REWARD_TEMPLATES: 'reward_templates',
  INGAME_POPUPS: 'ingame_popups',
  OPERATION_EVENTS: 'operation_events',
  SERVERS: 'servers',
  MESSAGE_TEMPLATES: 'message_templates',
  VARS: 'vars',
} as const;

export type Resource = (typeof RESOURCES)[keyof typeof RESOURCES];

// ==================== Resource Scope Mapping ====================

export const RESOURCE_SCOPES: Record<Resource, Scope> = {
  // System
  [RESOURCES.ORGANISATIONS]: SCOPES.SYSTEM,
  [RESOURCES.SYSTEM_CONFIG]: SCOPES.SYSTEM,
  [RESOURCES.SYSTEM_MONITORING]: SCOPES.SYSTEM,

  // Org
  [RESOURCES.USERS]: SCOPES.ORG,
  [RESOURCES.GROUPS]: SCOPES.ORG,
  [RESOURCES.ROLES]: SCOPES.ORG,
  [RESOURCES.INVITATIONS]: SCOPES.ORG,
  [RESOURCES.PROJECTS]: SCOPES.ORG,
  [RESOURCES.AUDIT_LOGS]: SCOPES.ORG,
  [RESOURCES.SYSTEM_SETTINGS]: SCOPES.ORG,
  [RESOURCES.ADMIN_TOKENS]: SCOPES.ORG,
  [RESOURCES.IP_WHITELIST]: SCOPES.ORG,
  [RESOURCES.ACCOUNT_WHITELIST]: SCOPES.ORG,
  [RESOURCES.INTEGRATIONS]: SCOPES.ORG,
  [RESOURCES.TRANSLATION]: SCOPES.ORG,
  [RESOURCES.CONSOLE]: SCOPES.ORG,
  [RESOURCES.CHAT]: SCOPES.ORG,
  [RESOURCES.MONITORING]: SCOPES.ORG,
  [RESOURCES.OPEN_API]: SCOPES.ORG,
  [RESOURCES.SCHEDULER]: SCOPES.ORG,
  [RESOURCES.EVENT_LENS]: SCOPES.ORG,
  [RESOURCES.CRASH_EVENTS]: SCOPES.PROJECT,
  [RESOURCES.REALTIME_EVENTS]: SCOPES.ORG,

  // Project
  [RESOURCES.FEATURES]: SCOPES.PROJECT,
  [RESOURCES.SEGMENTS]: SCOPES.PROJECT,
  [RESOURCES.CONTEXT_FIELDS]: SCOPES.PROJECT,
  [RESOURCES.RELEASE_FLOWS]: SCOPES.PROJECT,
  [RESOURCES.TAGS]: SCOPES.PROJECT,
  [RESOURCES.PLANNING_DATA]: SCOPES.ENV,
  [RESOURCES.SERVICE_ACCOUNTS]: SCOPES.PROJECT,
  [RESOURCES.SIGNAL_ENDPOINTS]: SCOPES.PROJECT,
  [RESOURCES.ACTIONS]: SCOPES.PROJECT,
  [RESOURCES.DATA]: SCOPES.PROJECT,
  [RESOURCES.UNKNOWN_FLAGS]: SCOPES.PROJECT,
  [RESOURCES.IMPACT_METRICS]: SCOPES.PROJECT,

  // Env
  [RESOURCES.ENVIRONMENTS]: SCOPES.ENV,
  [RESOURCES.ENV_FEATURES]: SCOPES.ENV,
  [RESOURCES.CHANGE_REQUESTS]: SCOPES.ENV,
  [RESOURCES.ENV_KEYS]: SCOPES.ENV,
  [RESOURCES.CLIENT_VERSIONS]: SCOPES.ENV,
  [RESOURCES.GAME_WORLDS]: SCOPES.ENV,
  [RESOURCES.MAINTENANCE]: SCOPES.ENV,
  [RESOURCES.MAINTENANCE_TEMPLATES]: SCOPES.ENV,
  [RESOURCES.SERVICE_NOTICES]: SCOPES.ENV,
  [RESOURCES.BANNERS]: SCOPES.ENV,
  [RESOURCES.COUPONS]: SCOPES.ENV,
  [RESOURCES.COUPON_SETTINGS]: SCOPES.ENV,
  [RESOURCES.SURVEYS]: SCOPES.ENV,
  [RESOURCES.STORE_PRODUCTS]: SCOPES.ENV,
  [RESOURCES.REWARD_TEMPLATES]: SCOPES.ENV,
  [RESOURCES.INGAME_POPUPS]: SCOPES.ENV,
  [RESOURCES.OPERATION_EVENTS]: SCOPES.ENV,
  [RESOURCES.SERVERS]: SCOPES.ENV,
  [RESOURCES.MESSAGE_TEMPLATES]: SCOPES.ENV,
  [RESOURCES.VARS]: SCOPES.ENV,
};

// ==================== Available Actions per Resource ====================

export const RESOURCE_ACTIONS: Record<Resource, readonly Action[]> = {
  // System
  [RESOURCES.ORGANISATIONS]: [
    ACTIONS.CREATE,
    ACTIONS.READ,
    ACTIONS.UPDATE,
    ACTIONS.DELETE,
  ],
  [RESOURCES.SYSTEM_CONFIG]: [ACTIONS.READ, ACTIONS.UPDATE],
  [RESOURCES.SYSTEM_MONITORING]: [ACTIONS.READ],

  // Org
  [RESOURCES.USERS]: [
    ACTIONS.CREATE,
    ACTIONS.READ,
    ACTIONS.UPDATE,
    ACTIONS.DELETE,
  ],
  [RESOURCES.GROUPS]: [
    ACTIONS.CREATE,
    ACTIONS.READ,
    ACTIONS.UPDATE,
    ACTIONS.DELETE,
  ],
  [RESOURCES.ROLES]: [
    ACTIONS.CREATE,
    ACTIONS.READ,
    ACTIONS.UPDATE,
    ACTIONS.DELETE,
  ],
  [RESOURCES.INVITATIONS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.DELETE],
  [RESOURCES.PROJECTS]: [
    ACTIONS.CREATE,
    ACTIONS.READ,
    ACTIONS.UPDATE,
    ACTIONS.DELETE,
  ],
  [RESOURCES.AUDIT_LOGS]: [ACTIONS.READ],
  [RESOURCES.SYSTEM_SETTINGS]: [ACTIONS.READ, ACTIONS.UPDATE],
  [RESOURCES.ADMIN_TOKENS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.DELETE],
  [RESOURCES.IP_WHITELIST]: [
    ACTIONS.CREATE,
    ACTIONS.READ,
    ACTIONS.UPDATE,
    ACTIONS.DELETE,
  ],
  [RESOURCES.ACCOUNT_WHITELIST]: [
    ACTIONS.CREATE,
    ACTIONS.READ,
    ACTIONS.UPDATE,
    ACTIONS.DELETE,
  ],
  [RESOURCES.INTEGRATIONS]: [ACTIONS.READ, ACTIONS.UPDATE],
  [RESOURCES.TRANSLATION]: [ACTIONS.READ, ACTIONS.UPDATE],
  [RESOURCES.CONSOLE]: [ACTIONS.ACCESS],
  [RESOURCES.CHAT]: [ACTIONS.ACCESS],
  [RESOURCES.MONITORING]: [ACTIONS.READ],
  [RESOURCES.OPEN_API]: [ACTIONS.READ],
  [RESOURCES.SCHEDULER]: [
    ACTIONS.READ,
    ACTIONS.CREATE,
    ACTIONS.UPDATE,
    ACTIONS.DELETE,
  ],
  [RESOURCES.EVENT_LENS]: [ACTIONS.READ, ACTIONS.UPDATE],
  [RESOURCES.CRASH_EVENTS]: [ACTIONS.READ],
  [RESOURCES.REALTIME_EVENTS]: [ACTIONS.READ],

  // Project
  [RESOURCES.FEATURES]: [
    ACTIONS.CREATE,
    ACTIONS.READ,
    ACTIONS.UPDATE,
    ACTIONS.DELETE,
  ],
  [RESOURCES.SEGMENTS]: [
    ACTIONS.CREATE,
    ACTIONS.READ,
    ACTIONS.UPDATE,
    ACTIONS.DELETE,
  ],
  [RESOURCES.CONTEXT_FIELDS]: [
    ACTIONS.CREATE,
    ACTIONS.READ,
    ACTIONS.UPDATE,
    ACTIONS.DELETE,
  ],
  [RESOURCES.RELEASE_FLOWS]: [
    ACTIONS.CREATE,
    ACTIONS.READ,
    ACTIONS.UPDATE,
    ACTIONS.DELETE,
  ],
  [RESOURCES.TAGS]: [
    ACTIONS.CREATE,
    ACTIONS.READ,
    ACTIONS.UPDATE,
    ACTIONS.DELETE,
  ],
  [RESOURCES.PLANNING_DATA]: [
    ACTIONS.CREATE,
    ACTIONS.READ,
    ACTIONS.UPDATE,
    ACTIONS.DELETE,
  ],
  [RESOURCES.SERVICE_ACCOUNTS]: [
    ACTIONS.CREATE,
    ACTIONS.READ,
    ACTIONS.UPDATE,
    ACTIONS.DELETE,
  ],
  [RESOURCES.SIGNAL_ENDPOINTS]: [
    ACTIONS.CREATE,
    ACTIONS.READ,
    ACTIONS.UPDATE,
    ACTIONS.DELETE,
  ],
  [RESOURCES.ACTIONS]: [
    ACTIONS.CREATE,
    ACTIONS.READ,
    ACTIONS.UPDATE,
    ACTIONS.DELETE,
  ],
  [RESOURCES.DATA]: [ACTIONS.READ, ACTIONS.UPDATE],
  [RESOURCES.UNKNOWN_FLAGS]: [ACTIONS.READ],
  [RESOURCES.IMPACT_METRICS]: [ACTIONS.READ, ACTIONS.UPDATE],

  // Env
  [RESOURCES.ENVIRONMENTS]: [ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
  [RESOURCES.ENV_FEATURES]: [ACTIONS.UPDATE],
  [RESOURCES.CHANGE_REQUESTS]: [ACTIONS.CREATE, ACTIONS.APPROVE, ACTIONS.SKIP],
  [RESOURCES.ENV_KEYS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.DELETE],
  [RESOURCES.CLIENT_VERSIONS]: [
    ACTIONS.CREATE,
    ACTIONS.READ,
    ACTIONS.UPDATE,
    ACTIONS.DELETE,
  ],
  [RESOURCES.GAME_WORLDS]: [
    ACTIONS.CREATE,
    ACTIONS.READ,
    ACTIONS.UPDATE,
    ACTIONS.DELETE,
  ],
  [RESOURCES.MAINTENANCE]: [ACTIONS.READ, ACTIONS.UPDATE],
  [RESOURCES.MAINTENANCE_TEMPLATES]: [
    ACTIONS.CREATE,
    ACTIONS.READ,
    ACTIONS.UPDATE,
    ACTIONS.DELETE,
  ],
  [RESOURCES.SERVICE_NOTICES]: [
    ACTIONS.CREATE,
    ACTIONS.READ,
    ACTIONS.UPDATE,
    ACTIONS.DELETE,
  ],
  [RESOURCES.BANNERS]: [
    ACTIONS.CREATE,
    ACTIONS.READ,
    ACTIONS.UPDATE,
    ACTIONS.DELETE,
  ],
  [RESOURCES.COUPONS]: [
    ACTIONS.CREATE,
    ACTIONS.READ,
    ACTIONS.UPDATE,
    ACTIONS.DELETE,
  ],
  [RESOURCES.COUPON_SETTINGS]: [ACTIONS.READ, ACTIONS.UPDATE],
  [RESOURCES.SURVEYS]: [
    ACTIONS.CREATE,
    ACTIONS.READ,
    ACTIONS.UPDATE,
    ACTIONS.DELETE,
  ],
  [RESOURCES.STORE_PRODUCTS]: [
    ACTIONS.CREATE,
    ACTIONS.READ,
    ACTIONS.UPDATE,
    ACTIONS.DELETE,
  ],
  [RESOURCES.REWARD_TEMPLATES]: [
    ACTIONS.CREATE,
    ACTIONS.READ,
    ACTIONS.UPDATE,
    ACTIONS.DELETE,
  ],
  [RESOURCES.INGAME_POPUPS]: [
    ACTIONS.CREATE,
    ACTIONS.READ,
    ACTIONS.UPDATE,
    ACTIONS.DELETE,
  ],
  [RESOURCES.OPERATION_EVENTS]: [
    ACTIONS.CREATE,
    ACTIONS.READ,
    ACTIONS.UPDATE,
    ACTIONS.DELETE,
  ],
  [RESOURCES.SERVERS]: [
    ACTIONS.CREATE,
    ACTIONS.READ,
    ACTIONS.UPDATE,
    ACTIONS.DELETE,
  ],
  [RESOURCES.MESSAGE_TEMPLATES]: [
    ACTIONS.CREATE,
    ACTIONS.READ,
    ACTIONS.UPDATE,
    ACTIONS.DELETE,
  ],
  [RESOURCES.VARS]: [
    ACTIONS.CREATE,
    ACTIONS.READ,
    ACTIONS.UPDATE,
    ACTIONS.DELETE,
  ],
};

// ==================== Permission Constants (P) ====================
// Pre-built permission strings for type-safe usage.
// Usage: import { P } from '@gatrix/shared/permissions';
//        requirePermission(P.USERS_READ)

function perm(resource: string, action: string): string {
  return `${resource}:${action}`;
}

export const P = {
  // Wildcard
  ALL: '*:*',

  // System
  ORGANISATIONS_CREATE: perm(RESOURCES.ORGANISATIONS, ACTIONS.CREATE),
  ORGANISATIONS_READ: perm(RESOURCES.ORGANISATIONS, ACTIONS.READ),
  ORGANISATIONS_UPDATE: perm(RESOURCES.ORGANISATIONS, ACTIONS.UPDATE),
  ORGANISATIONS_DELETE: perm(RESOURCES.ORGANISATIONS, ACTIONS.DELETE),
  SYSTEM_CONFIG_READ: perm(RESOURCES.SYSTEM_CONFIG, ACTIONS.READ),
  SYSTEM_CONFIG_UPDATE: perm(RESOURCES.SYSTEM_CONFIG, ACTIONS.UPDATE),
  SYSTEM_MONITORING_READ: perm(RESOURCES.SYSTEM_MONITORING, ACTIONS.READ),

  // Org - Users
  USERS_CREATE: perm(RESOURCES.USERS, ACTIONS.CREATE),
  USERS_READ: perm(RESOURCES.USERS, ACTIONS.READ),
  USERS_UPDATE: perm(RESOURCES.USERS, ACTIONS.UPDATE),
  USERS_DELETE: perm(RESOURCES.USERS, ACTIONS.DELETE),

  // Org - Groups
  GROUPS_CREATE: perm(RESOURCES.GROUPS, ACTIONS.CREATE),
  GROUPS_READ: perm(RESOURCES.GROUPS, ACTIONS.READ),
  GROUPS_UPDATE: perm(RESOURCES.GROUPS, ACTIONS.UPDATE),
  GROUPS_DELETE: perm(RESOURCES.GROUPS, ACTIONS.DELETE),

  // Org - Roles
  ROLES_CREATE: perm(RESOURCES.ROLES, ACTIONS.CREATE),
  ROLES_READ: perm(RESOURCES.ROLES, ACTIONS.READ),
  ROLES_UPDATE: perm(RESOURCES.ROLES, ACTIONS.UPDATE),
  ROLES_DELETE: perm(RESOURCES.ROLES, ACTIONS.DELETE),

  // Org - Invitations
  INVITATIONS_CREATE: perm(RESOURCES.INVITATIONS, ACTIONS.CREATE),
  INVITATIONS_READ: perm(RESOURCES.INVITATIONS, ACTIONS.READ),
  INVITATIONS_DELETE: perm(RESOURCES.INVITATIONS, ACTIONS.DELETE),

  // Org - Projects
  PROJECTS_CREATE: perm(RESOURCES.PROJECTS, ACTIONS.CREATE),
  PROJECTS_READ: perm(RESOURCES.PROJECTS, ACTIONS.READ),
  PROJECTS_UPDATE: perm(RESOURCES.PROJECTS, ACTIONS.UPDATE),
  PROJECTS_DELETE: perm(RESOURCES.PROJECTS, ACTIONS.DELETE),

  // Org - Audit/Settings/Tokens
  AUDIT_LOGS_READ: perm(RESOURCES.AUDIT_LOGS, ACTIONS.READ),
  SYSTEM_SETTINGS_READ: perm(RESOURCES.SYSTEM_SETTINGS, ACTIONS.READ),
  SYSTEM_SETTINGS_UPDATE: perm(RESOURCES.SYSTEM_SETTINGS, ACTIONS.UPDATE),
  ADMIN_TOKENS_CREATE: perm(RESOURCES.ADMIN_TOKENS, ACTIONS.CREATE),
  ADMIN_TOKENS_READ: perm(RESOURCES.ADMIN_TOKENS, ACTIONS.READ),
  ADMIN_TOKENS_DELETE: perm(RESOURCES.ADMIN_TOKENS, ACTIONS.DELETE),

  // Org - Security
  IP_WHITELIST_CREATE: perm(RESOURCES.IP_WHITELIST, ACTIONS.CREATE),
  IP_WHITELIST_READ: perm(RESOURCES.IP_WHITELIST, ACTIONS.READ),
  IP_WHITELIST_UPDATE: perm(RESOURCES.IP_WHITELIST, ACTIONS.UPDATE),
  IP_WHITELIST_DELETE: perm(RESOURCES.IP_WHITELIST, ACTIONS.DELETE),
  ACCOUNT_WHITELIST_CREATE: perm(RESOURCES.ACCOUNT_WHITELIST, ACTIONS.CREATE),
  ACCOUNT_WHITELIST_READ: perm(RESOURCES.ACCOUNT_WHITELIST, ACTIONS.READ),
  ACCOUNT_WHITELIST_UPDATE: perm(RESOURCES.ACCOUNT_WHITELIST, ACTIONS.UPDATE),
  ACCOUNT_WHITELIST_DELETE: perm(RESOURCES.ACCOUNT_WHITELIST, ACTIONS.DELETE),

  // Org - Integrations/Translation
  INTEGRATIONS_READ: perm(RESOURCES.INTEGRATIONS, ACTIONS.READ),
  INTEGRATIONS_UPDATE: perm(RESOURCES.INTEGRATIONS, ACTIONS.UPDATE),
  TRANSLATION_READ: perm(RESOURCES.TRANSLATION, ACTIONS.READ),
  TRANSLATION_UPDATE: perm(RESOURCES.TRANSLATION, ACTIONS.UPDATE),

  // Org - Special access
  CONSOLE_ACCESS: perm(RESOURCES.CONSOLE, ACTIONS.ACCESS),
  CHAT_ACCESS: perm(RESOURCES.CHAT, ACTIONS.ACCESS),

  // Org - Read-only
  MONITORING_READ: perm(RESOURCES.MONITORING, ACTIONS.READ),
  OPEN_API_READ: perm(RESOURCES.OPEN_API, ACTIONS.READ),
  CRASH_EVENTS_READ: perm(RESOURCES.CRASH_EVENTS, ACTIONS.READ),
  REALTIME_EVENTS_READ: perm(RESOURCES.REALTIME_EVENTS, ACTIONS.READ),

  // Org - Scheduler
  SCHEDULER_CREATE: perm(RESOURCES.SCHEDULER, ACTIONS.CREATE),
  SCHEDULER_READ: perm(RESOURCES.SCHEDULER, ACTIONS.READ),
  SCHEDULER_UPDATE: perm(RESOURCES.SCHEDULER, ACTIONS.UPDATE),
  SCHEDULER_DELETE: perm(RESOURCES.SCHEDULER, ACTIONS.DELETE),

  // Org - Event Lens
  EVENT_LENS_READ: perm(RESOURCES.EVENT_LENS, ACTIONS.READ),
  EVENT_LENS_UPDATE: perm(RESOURCES.EVENT_LENS, ACTIONS.UPDATE),

  // Project - Features
  FEATURES_CREATE: perm(RESOURCES.FEATURES, ACTIONS.CREATE),
  FEATURES_READ: perm(RESOURCES.FEATURES, ACTIONS.READ),
  FEATURES_UPDATE: perm(RESOURCES.FEATURES, ACTIONS.UPDATE),
  FEATURES_DELETE: perm(RESOURCES.FEATURES, ACTIONS.DELETE),

  // Project - Segments
  SEGMENTS_CREATE: perm(RESOURCES.SEGMENTS, ACTIONS.CREATE),
  SEGMENTS_READ: perm(RESOURCES.SEGMENTS, ACTIONS.READ),
  SEGMENTS_UPDATE: perm(RESOURCES.SEGMENTS, ACTIONS.UPDATE),
  SEGMENTS_DELETE: perm(RESOURCES.SEGMENTS, ACTIONS.DELETE),

  // Project - Context Fields
  CONTEXT_FIELDS_CREATE: perm(RESOURCES.CONTEXT_FIELDS, ACTIONS.CREATE),
  CONTEXT_FIELDS_READ: perm(RESOURCES.CONTEXT_FIELDS, ACTIONS.READ),
  CONTEXT_FIELDS_UPDATE: perm(RESOURCES.CONTEXT_FIELDS, ACTIONS.UPDATE),
  CONTEXT_FIELDS_DELETE: perm(RESOURCES.CONTEXT_FIELDS, ACTIONS.DELETE),

  // Project - Release Flows
  RELEASE_FLOWS_CREATE: perm(RESOURCES.RELEASE_FLOWS, ACTIONS.CREATE),
  RELEASE_FLOWS_READ: perm(RESOURCES.RELEASE_FLOWS, ACTIONS.READ),
  RELEASE_FLOWS_UPDATE: perm(RESOURCES.RELEASE_FLOWS, ACTIONS.UPDATE),
  RELEASE_FLOWS_DELETE: perm(RESOURCES.RELEASE_FLOWS, ACTIONS.DELETE),

  // Project - Tags
  TAGS_CREATE: perm(RESOURCES.TAGS, ACTIONS.CREATE),
  TAGS_READ: perm(RESOURCES.TAGS, ACTIONS.READ),
  TAGS_UPDATE: perm(RESOURCES.TAGS, ACTIONS.UPDATE),
  TAGS_DELETE: perm(RESOURCES.TAGS, ACTIONS.DELETE),

  // Project - Planning Data
  PLANNING_DATA_CREATE: perm(RESOURCES.PLANNING_DATA, ACTIONS.CREATE),
  PLANNING_DATA_READ: perm(RESOURCES.PLANNING_DATA, ACTIONS.READ),
  PLANNING_DATA_UPDATE: perm(RESOURCES.PLANNING_DATA, ACTIONS.UPDATE),
  PLANNING_DATA_DELETE: perm(RESOURCES.PLANNING_DATA, ACTIONS.DELETE),

  // Project - Service Accounts
  SERVICE_ACCOUNTS_CREATE: perm(RESOURCES.SERVICE_ACCOUNTS, ACTIONS.CREATE),
  SERVICE_ACCOUNTS_READ: perm(RESOURCES.SERVICE_ACCOUNTS, ACTIONS.READ),
  SERVICE_ACCOUNTS_UPDATE: perm(RESOURCES.SERVICE_ACCOUNTS, ACTIONS.UPDATE),
  SERVICE_ACCOUNTS_DELETE: perm(RESOURCES.SERVICE_ACCOUNTS, ACTIONS.DELETE),

  // Project - Signal Endpoints
  SIGNAL_ENDPOINTS_CREATE: perm(RESOURCES.SIGNAL_ENDPOINTS, ACTIONS.CREATE),
  SIGNAL_ENDPOINTS_READ: perm(RESOURCES.SIGNAL_ENDPOINTS, ACTIONS.READ),
  SIGNAL_ENDPOINTS_UPDATE: perm(RESOURCES.SIGNAL_ENDPOINTS, ACTIONS.UPDATE),
  SIGNAL_ENDPOINTS_DELETE: perm(RESOURCES.SIGNAL_ENDPOINTS, ACTIONS.DELETE),

  // Project - Actions
  ACTIONS_CREATE: perm(RESOURCES.ACTIONS, ACTIONS.CREATE),
  ACTIONS_READ: perm(RESOURCES.ACTIONS, ACTIONS.READ),
  ACTIONS_UPDATE: perm(RESOURCES.ACTIONS, ACTIONS.UPDATE),
  ACTIONS_DELETE: perm(RESOURCES.ACTIONS, ACTIONS.DELETE),

  // Project - Data
  DATA_READ: perm(RESOURCES.DATA, ACTIONS.READ),
  DATA_UPDATE: perm(RESOURCES.DATA, ACTIONS.UPDATE),

  // Project - Read-only
  UNKNOWN_FLAGS_READ: perm(RESOURCES.UNKNOWN_FLAGS, ACTIONS.READ),
  IMPACT_METRICS_READ: perm(RESOURCES.IMPACT_METRICS, ACTIONS.READ),
  IMPACT_METRICS_UPDATE: perm(RESOURCES.IMPACT_METRICS, ACTIONS.UPDATE),

  // Env - Environments
  ENVIRONMENTS_READ: perm(RESOURCES.ENVIRONMENTS, ACTIONS.READ),
  ENVIRONMENTS_UPDATE: perm(RESOURCES.ENVIRONMENTS, ACTIONS.UPDATE),
  ENVIRONMENTS_DELETE: perm(RESOURCES.ENVIRONMENTS, ACTIONS.DELETE),

  // Env - Features (env-level overrides)
  ENV_FEATURES_UPDATE: perm(RESOURCES.ENV_FEATURES, ACTIONS.UPDATE),

  // Env - Change Requests
  CHANGE_REQUESTS_CREATE: perm(RESOURCES.CHANGE_REQUESTS, ACTIONS.CREATE),
  CHANGE_REQUESTS_APPROVE: perm(RESOURCES.CHANGE_REQUESTS, ACTIONS.APPROVE),
  CHANGE_REQUESTS_SKIP: perm(RESOURCES.CHANGE_REQUESTS, ACTIONS.SKIP),

  // Env - Keys
  ENV_KEYS_CREATE: perm(RESOURCES.ENV_KEYS, ACTIONS.CREATE),
  ENV_KEYS_READ: perm(RESOURCES.ENV_KEYS, ACTIONS.READ),
  ENV_KEYS_DELETE: perm(RESOURCES.ENV_KEYS, ACTIONS.DELETE),

  // Env - Client Versions
  CLIENT_VERSIONS_CREATE: perm(RESOURCES.CLIENT_VERSIONS, ACTIONS.CREATE),
  CLIENT_VERSIONS_READ: perm(RESOURCES.CLIENT_VERSIONS, ACTIONS.READ),
  CLIENT_VERSIONS_UPDATE: perm(RESOURCES.CLIENT_VERSIONS, ACTIONS.UPDATE),
  CLIENT_VERSIONS_DELETE: perm(RESOURCES.CLIENT_VERSIONS, ACTIONS.DELETE),

  // Env - Game Worlds
  GAME_WORLDS_CREATE: perm(RESOURCES.GAME_WORLDS, ACTIONS.CREATE),
  GAME_WORLDS_READ: perm(RESOURCES.GAME_WORLDS, ACTIONS.READ),
  GAME_WORLDS_UPDATE: perm(RESOURCES.GAME_WORLDS, ACTIONS.UPDATE),
  GAME_WORLDS_DELETE: perm(RESOURCES.GAME_WORLDS, ACTIONS.DELETE),

  // Env - Maintenance
  MAINTENANCE_READ: perm(RESOURCES.MAINTENANCE, ACTIONS.READ),
  MAINTENANCE_UPDATE: perm(RESOURCES.MAINTENANCE, ACTIONS.UPDATE),
  MAINTENANCE_TEMPLATES_CREATE: perm(
    RESOURCES.MAINTENANCE_TEMPLATES,
    ACTIONS.CREATE
  ),
  MAINTENANCE_TEMPLATES_READ: perm(
    RESOURCES.MAINTENANCE_TEMPLATES,
    ACTIONS.READ
  ),
  MAINTENANCE_TEMPLATES_UPDATE: perm(
    RESOURCES.MAINTENANCE_TEMPLATES,
    ACTIONS.UPDATE
  ),
  MAINTENANCE_TEMPLATES_DELETE: perm(
    RESOURCES.MAINTENANCE_TEMPLATES,
    ACTIONS.DELETE
  ),

  // Env - Service Notices
  SERVICE_NOTICES_CREATE: perm(RESOURCES.SERVICE_NOTICES, ACTIONS.CREATE),
  SERVICE_NOTICES_READ: perm(RESOURCES.SERVICE_NOTICES, ACTIONS.READ),
  SERVICE_NOTICES_UPDATE: perm(RESOURCES.SERVICE_NOTICES, ACTIONS.UPDATE),
  SERVICE_NOTICES_DELETE: perm(RESOURCES.SERVICE_NOTICES, ACTIONS.DELETE),

  // Env - Banners
  BANNERS_CREATE: perm(RESOURCES.BANNERS, ACTIONS.CREATE),
  BANNERS_READ: perm(RESOURCES.BANNERS, ACTIONS.READ),
  BANNERS_UPDATE: perm(RESOURCES.BANNERS, ACTIONS.UPDATE),
  BANNERS_DELETE: perm(RESOURCES.BANNERS, ACTIONS.DELETE),

  // Env - Coupons
  COUPONS_CREATE: perm(RESOURCES.COUPONS, ACTIONS.CREATE),
  COUPONS_READ: perm(RESOURCES.COUPONS, ACTIONS.READ),
  COUPONS_UPDATE: perm(RESOURCES.COUPONS, ACTIONS.UPDATE),
  COUPONS_DELETE: perm(RESOURCES.COUPONS, ACTIONS.DELETE),
  COUPON_SETTINGS_READ: perm(RESOURCES.COUPON_SETTINGS, ACTIONS.READ),
  COUPON_SETTINGS_UPDATE: perm(RESOURCES.COUPON_SETTINGS, ACTIONS.UPDATE),

  // Env - Surveys
  SURVEYS_CREATE: perm(RESOURCES.SURVEYS, ACTIONS.CREATE),
  SURVEYS_READ: perm(RESOURCES.SURVEYS, ACTIONS.READ),
  SURVEYS_UPDATE: perm(RESOURCES.SURVEYS, ACTIONS.UPDATE),
  SURVEYS_DELETE: perm(RESOURCES.SURVEYS, ACTIONS.DELETE),

  // Env - Store Products
  STORE_PRODUCTS_CREATE: perm(RESOURCES.STORE_PRODUCTS, ACTIONS.CREATE),
  STORE_PRODUCTS_READ: perm(RESOURCES.STORE_PRODUCTS, ACTIONS.READ),
  STORE_PRODUCTS_UPDATE: perm(RESOURCES.STORE_PRODUCTS, ACTIONS.UPDATE),
  STORE_PRODUCTS_DELETE: perm(RESOURCES.STORE_PRODUCTS, ACTIONS.DELETE),

  // Env - Reward Templates
  REWARD_TEMPLATES_CREATE: perm(RESOURCES.REWARD_TEMPLATES, ACTIONS.CREATE),
  REWARD_TEMPLATES_READ: perm(RESOURCES.REWARD_TEMPLATES, ACTIONS.READ),
  REWARD_TEMPLATES_UPDATE: perm(RESOURCES.REWARD_TEMPLATES, ACTIONS.UPDATE),
  REWARD_TEMPLATES_DELETE: perm(RESOURCES.REWARD_TEMPLATES, ACTIONS.DELETE),

  // Env - Ingame Popups
  INGAME_POPUPS_CREATE: perm(RESOURCES.INGAME_POPUPS, ACTIONS.CREATE),
  INGAME_POPUPS_READ: perm(RESOURCES.INGAME_POPUPS, ACTIONS.READ),
  INGAME_POPUPS_UPDATE: perm(RESOURCES.INGAME_POPUPS, ACTIONS.UPDATE),
  INGAME_POPUPS_DELETE: perm(RESOURCES.INGAME_POPUPS, ACTIONS.DELETE),

  // Env - Operation Events
  OPERATION_EVENTS_CREATE: perm(RESOURCES.OPERATION_EVENTS, ACTIONS.CREATE),
  OPERATION_EVENTS_READ: perm(RESOURCES.OPERATION_EVENTS, ACTIONS.READ),
  OPERATION_EVENTS_UPDATE: perm(RESOURCES.OPERATION_EVENTS, ACTIONS.UPDATE),
  OPERATION_EVENTS_DELETE: perm(RESOURCES.OPERATION_EVENTS, ACTIONS.DELETE),

  // Env - Servers
  SERVERS_CREATE: perm(RESOURCES.SERVERS, ACTIONS.CREATE),
  SERVERS_READ: perm(RESOURCES.SERVERS, ACTIONS.READ),
  SERVERS_UPDATE: perm(RESOURCES.SERVERS, ACTIONS.UPDATE),
  SERVERS_DELETE: perm(RESOURCES.SERVERS, ACTIONS.DELETE),

  // Env - Message Templates
  MESSAGE_TEMPLATES_CREATE: perm(RESOURCES.MESSAGE_TEMPLATES, ACTIONS.CREATE),
  MESSAGE_TEMPLATES_READ: perm(RESOURCES.MESSAGE_TEMPLATES, ACTIONS.READ),
  MESSAGE_TEMPLATES_UPDATE: perm(RESOURCES.MESSAGE_TEMPLATES, ACTIONS.UPDATE),
  MESSAGE_TEMPLATES_DELETE: perm(RESOURCES.MESSAGE_TEMPLATES, ACTIONS.DELETE),

  // Env - Vars
  VARS_CREATE: perm(RESOURCES.VARS, ACTIONS.CREATE),
  VARS_READ: perm(RESOURCES.VARS, ACTIONS.READ),
  VARS_UPDATE: perm(RESOURCES.VARS, ACTIONS.UPDATE),
  VARS_DELETE: perm(RESOURCES.VARS, ACTIONS.DELETE),
} as const;

export type PermissionKey = keyof typeof P;
