{
 "title": "Gatrix Logs",
 "tags": [
  "gatrix",
  "logs"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {}
   },
   {
    "name": "level",
    "label": "Level",
    "query": {}
   },
   { "name": "hostname", "label": "Hostname", "query": "label_values(hostname)" },
   { "name": "internalIp", "label": "Internal IP", "query": "label_values(internalIp)" },
   { "name": "externalIp", "label": "External IP", "query": "label_values(externalIp)" },
   {
    "name": "search",
    "label": "Search (message, url, method, etc.)"
   }
  ]
 },
 "panels": [
  {
   "title": "Log volume by level",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (logLevel) (count_over_time({job=\"gatrix\", service=~\"$service\", internalIp=~\"$internalIp\", externalIp=~\"$externalIp\"} | json | level=~\"$level\" | hostname=~\"$hostname\" | label_format logLevel=\"{{.level}}\" | line_format \"{{.}}\" |~ \"(?i)$search\" [1m]))",
     "legendFormat": "{{logLevel}}"
    }
   ]
  },
  {
   "title": "Error logs per service",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (service) (count_over_time({job=\"gatrix\", service=~\"$service\", internalIp=~\"$internalIp\", externalIp=~\"$externalIp\"} | json | level=~\"error|fatal\" | hostname=~\"$hostname\" | line_format \"{{.}}\" |~ \"(?i)$search\" [1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{job=\"gatrix\", service=~\"$service\", internalIp=~\"$internalIp\", externalIp=~\"$externalIp\"} | json | json responseBody=\"responseBody\", queryParams=\"queryParams\" | level=~\"$level\" | hostname=~\"$hostname\" | line_format `[{{.level}}] [{{.service}}] {{.message}}` |~ \"(?i)$search\""
    }
   ]
  }
 ]
}