const fs = require('fs');
const path = require('path');

const base = 'c:/work/uwo/gatrix';
const koreanRegex = /[\uAC00-\uD7AF\u3131-\u3163\u318E]/;

// Extended translations - round 2
// Focus on partial replacements and common patterns missed in round 1
const translations = [
  // Partially-translated patterns from round 1 (word "Used" replaced "사용")
  ['Used자', 'user'],
  ['Used자만', 'users only'],
  ['Used자에게', 'to user'],
  ['Used자의', "user's"],
  ['Used자가', 'user'],
  ['Used자를', 'user'],
  ['Used자들', 'users'],
  ['Used자에', 'to user'],
  ['Used자만)', 'users only)'],
  // Partially-translated patterns from round 1 (other partial translations)
  ['Settings과', 'settings and'],
  ['Settings에서', 'from settings'],
  ['Settings으로', 'as settings'],
  ['Settings이', 'settings is'],
  ['Settings을', 'settings'],
  ['Settings인', 'is settings'],
  ['Settings한', 'configured'],
  ['Settings하', 'configure'],
  ['Settings된', 'configured'],
  ['Settings해', 'configure'],
  ['Active된', 'activated'],
  ['Active되', 'activate'],
  ['Active하', 'activate'],
  ['Active화', 'activated'],
  ['Active에', 'on active'],
  ['Active인', 'is active'],
  ['Active일', 'if active'],
  ['Unregister하', 'unregister'],
  ['Convert to integer로', 'to integer'],
  ['Initialization하', 'initialize'],
  ['Initialization되', 'initialized'],
  ['Initialization이', 'initialization is'],
  ['Initialization한', 'initialized'],
  ['Initialization에', 'in initialization'],
  ['Failed해도', 'even if failed'],
  ['Failed한', 'failed'],
  ['Failed해', 'failed'],
  ['Failed했', 'failed'],
  ['Failed되', 'failed'],
  ['Refresh하', 'refresh'],
  ['Refresh되', 'refreshed'],
  ['Refresh된', 'refreshed'],
  ['Refresh를', 'refresh'],
  ['Refresh에', 'refresh'],
  ['Refresh의', 'of refresh'],
  // UI Korean comments
  ['별개', 'independent'],
  ['별도', 'separately'],
  ['별도로', 'separately'],
  ['예를 들어', 'for example'],
  ['예:', 'e.g.:'],
  ['또는', 'or'],
  ['안됨', 'not allowed'],
  ['안함', 'not done'],
  ['때문에', 'because'],
  ['때문', 'because'],
  ['위해', 'for'],
  ['위한', 'for'],
  ['이후', 'after'],
  ['이전', 'before'],
  ['이전의', 'previous'],
  ['이전에', 'before'],
  ['경우에만', 'only when'],
  ['경우에', 'in case of'],
  ['경우만', 'only in case of'],
  ['경우', 'case'],
  ['경우의', 'of case'],
  ['경우는', 'case is'],
  ['경우가', 'case is'],
  ['아닌', 'not'],
  ['아닌지', 'whether not'],
  ['있는 경우', 'if exists'],
  ['있는', 'existing'],
  ['있으면', 'if exists'],
  ['있을', 'if exists'],
  ['있는지', 'whether exists'],
  ['없는', 'non-existing'],
  ['없으면', 'if not exists'],
  ['없는 경우', 'if not exists'],
  ['없을', 'if not exists'],
  ['없음', 'none'],
  ['확인하', 'check'],
  ['확인한', 'checked'],
  ['대한', 'for'],
  ['변환된', 'converted'],
  ['변환된다', 'is converted'],
  ['변환하', 'convert'],
  ['변환', 'conversion'],
  ['전환', 'switch'],
  ['포함', 'include'],
  ['포함된', 'included'],
  ['포함하', 'include'],
  ['포함되어', 'included'],
  ['추가된', 'added'],
  ['추가되', 'added'],
  ['추가하', 'add'],
  ['추가', 'add'],
  ['제거하', 'remove'],
  ['제거된', 'removed'],
  ['제거', 'remove'],
  ['조회하', 'retrieve'],
  ['조회된', 'retrieved'],
  ['조회', 'query'],
  ['반환하', 'return'],
  ['반환된', 'returned'],
  ['반환', 'return'],
  ['설정되', 'set'],
  ['설정하', 'set'],
  ['설정된', 'configured'],
  ['설정이', 'settings'],
  ['설정을', 'settings'],
  ['설정에', 'in settings'],
  ['설정값', 'setting value'],
  ['갱신', 'refresh'],
  ['업데이트', 'update'],
  ['업데이트되', 'updated'],
  ['저장하', 'save'],
  ['저장된', 'saved'],
  ['삭제하', 'delete'],
  ['삭제된', 'deleted'],
  ['생성하', 'create'],
  ['생성된', 'created'],
  ['수정하', 'modify'],
  ['수정된', 'modified'],
  ['처리하', 'handle'],
  ['처리된', 'handled'],
  ['호출하', 'call'],
  ['호출된', 'called'],
  ['호출', 'call'],
  ['실행하', 'execute'],
  ['실행된', 'executed'],
  ['실행', 'execution'],
  ['시작하', 'start'],
  ['시작된', 'started'],
  ['시작', 'start'],
  ['종료하', 'end'],
  ['종료된', 'ended'],
  ['종료', 'end'],
  ['완료하', 'complete'],
  ['완료된', 'completed'],
  ['완료', 'completed'],
  ['전에', 'before'],
  ['후에', 'after'],
  ['동안', 'during'],
  ['까지', 'until'],
  ['부터', 'from'],
  ['로부터', 'from'],
  ['여부', 'whether'],
  ['유무', 'presence'],
  ['동작', 'behavior'],
  ['동작하', 'work'],
  ['필요', 'required'],
  ['불필요', 'unnecessary'],
  ['가능', 'possible'],
  ['불가능', 'impossible'],
  ['문제', 'issue'],
  ['오류', 'error'],
  ['관련', 'related'],
  ['기타', 'other'],
  ['기본', 'default'],
  ['현재', 'current'],
  ['이전', 'previous'],
  ['다음', 'next'],
  ['같은', 'same'],
  ['다른', 'other'],
  ['모든', 'all'],
  ['각각', 'each'],
  ['하나', 'one'],
  ['아래', 'below'],
  ['위', 'above'],
  ['내부', 'internal'],
  ['외부', 'external'],
  ['전체', 'entire'],
  ['부분', 'partial'],
  ['일부', 'some'],
  ['연결', 'connection'],
  ['해제', 'release'],
  ['등록', 'registration'],
  ['해당', 'corresponding'],
  ['표시', 'display'],
  ['숨김', 'hidden'],
  ['클릭', 'click'],
  ['입력', 'input'],
  ['출력', 'output'],
  ['발생', 'occurred'],
  ['유지', 'maintain'],
  ['방지', 'prevent'],
  ['변경', 'change'],
  ['적용', 'apply'],
  ['구현', 'implementation'],
  ['임시', 'temporary'],
  ['구조', 'structure'],
  ['최종', 'final'],
  ['최초', 'first'],
  ['최신', 'latest'],
  ['최대', 'maximum'],
  ['최소', 'minimum'],
  ['정보', 'info'],
  ['값', 'value'],
  ['키', 'key'],
  ['형식', 'format'],
  ['타입', 'type'],
  ['크기', 'size'],
  ['길이', 'length'],
  ['개수', 'count'],
  ['갯수', 'count'],
  ['사이', 'between'],
  ['범위', 'range'],
  ['목록', 'list'],
  ['항목', 'item'],
  ['옵션', 'option'],
  ['파일', 'file'],
  ['경로', 'path'],
  ['폴더', 'folder'],
  ['메시지', 'message'],
  ['알림', 'notification'],
  ['스타일', 'style'],
  ['레이아웃', 'layout'],
  ['컴포넌트', 'component'],
  ['컴포넌트를', 'component'],
  ['페이지', 'page'],
  ['버튼', 'button'],
  ['아이콘', 'icon'],
  ['텍스트', 'text'],
  ['이미지', 'image'],
  ['링크', 'link'],
  ['탭', 'tab'],
  ['패널', 'panel'],
  ['카드', 'card'],
  ['목록', 'list'],
  ['테이블', 'table'],
  ['헤더', 'header'],
  ['풋터', 'footer'],
  ['사이드바', 'sidebar'],
  ['모달', 'modal'],
  ['다이얼로그', 'dialog'],
  ['팝업', 'popup'],
  ['메뉴', 'menu'],
  ['드롭다운', 'dropdown'],
  ['체크박스', 'checkbox'],
  ['라디오', 'radio'],
  ['스위치', 'switch'],
  ['슬라이더', 'slider'],
  ['프로그레스', 'progress'],
  ['스피너', 'spinner'],
  ['로딩', 'loading'],
  ['에러', 'error'],
  ['경고', 'warning'],
  ['정보', 'info'],
  ['성공', 'success'],
  ['실패', 'failure'],
  ['확인', 'confirm'],
  ['취소', 'cancel'],
  ['닫기', 'close'],
  ['열기', 'open'],
  ['저장', 'save'],
  ['삭제', 'delete'],
  ['수정', 'edit'],
  ['생성', 'create'],
  ['복사', 'copy'],
  ['붙여넣기', 'paste'],
  ['되돌리기', 'undo'],
  ['다시하기', 'redo'],
  ['새로고침', 'refresh'],
  ['검색', 'search'],
  ['필터', 'filter'],
  ['정렬', 'sort'],
  ['그룹', 'group'],
  ['카테고리', 'category'],
  ['태그', 'tag'],
  ['라벨', 'label'],
  ['배지', 'badge'],
  ['칩', 'chip'],
  ['아바타', 'avatar'],
  ['툴팁', 'tooltip'],
  ['스낵바', 'snackbar'],
  ['토스트', 'toast'],
  ['드로어', 'drawer'],
  ['앱바', 'app bar'],
  ['내비게이션', 'navigation'],
  ['브래드크럼', 'breadcrumb'],
  ['페이지네이션', 'pagination'],
  ['스텝퍼', 'stepper'],
  ['타임라인', 'timeline'],
  ['캘린더', 'calendar'],
  ['리스트', 'list'],
  ['그리드', 'grid'],
  ['플렉스', 'flex'],
  ['컨테이너', 'container'],
  ['래퍼', 'wrapper'],
  ['섹션', 'section'],
  ['영역', 'area'],
  ['패딩', 'padding'],
  ['마진', 'margin'],
  ['보더', 'border'],
  ['라운드', 'round'],
  ['그림자', 'shadow'],
  ['투명도', 'opacity'],
  ['배경', 'background'],
  ['색상', 'color'],
  ['폰트', 'font'],
  ['크기', 'size'],
  ['굵기', 'weight'],
  ['줄간격', 'line height'],
  ['간격', 'spacing'],
  ['정렬', 'alignment'],
  ['가로', 'horizontal'],
  ['세로', 'vertical'],
  ['너비', 'width'],
  ['높이', 'height'],
  ['디바운스', 'debounce'],
  ['디바운싱', 'debouncing'],
  ['쓰로틀링', 'throttling'],
  ['캐싱', 'caching'],
  ['렌더링', 'rendering'],
  ['리렌더링', 're-rendering'],
  ['마운트', 'mount'],
  ['언마운트', 'unmount'],
  ['이슈', 'issue'],
  ['버그', 'bug'],
  ['임시', 'temporary'],
  ['참고', 'reference'],
  ['프록시', 'proxy'],
  ['서버', 'server'],
  ['클라이언트', 'client'],
  ['프론트엔드', 'frontend'],
  ['백엔드', 'backend'],
  ['데이터베이스', 'database'],
  ['쿼리', 'query'],
  ['응답', 'response'],
  ['요청', 'request'],
  ['인증', 'authentication'],
  ['권한', 'permission'],
  ['토큰', 'token'],
  ['세션', 'session'],
  ['쿠키', 'cookie'],
  ['캐시', 'cache'],
  ['로컬스토리지', 'localStorage'],
  ['환경변수', 'environment variable'],
  ['스크립트', 'script'],
  ['유틸리티', 'utility'],
  ['헬퍼', 'helper'],
  ['핸들러', 'handler'],
  ['콜백', 'callback'],
  ['프로미스', 'promise'],
  ['비동기', 'async'],
  ['동기', 'sync'],
  ['이벤트', 'event'],
  ['리스너', 'listener'],
  ['옵저버', 'observer'],
  ['구독', 'subscription'],
  ['발행', 'publish'],
  ['미들웨어', 'middleware'],
  ['라우팅', 'routing'],
  ['엔드포인트', 'endpoint'],
  ['파라미터', 'parameter'],
  ['인터페이스', 'interface'],
  ['클래스', 'class'],
  ['인스턴스', 'instance'],
  ['모듈', 'module'],
  ['패키지', 'package'],
  ['라이브러리', 'library'],
  ['프레임워크', 'framework'],
  ['웹소켓', 'WebSocket'],
  ['스키마', 'schema'],
  ['마이그레이션', 'migration'],
  ['트랜잭션', 'transaction'],
  ['인덱스', 'index'],
  ['커밋', 'commit'],
  ['롤백', 'rollback'],
  ['점검', 'maintenance'],
  ['유효성', 'validity'],
  ['검증', 'validation'],
  ['초기화', 'initialization'],
  ['상태', 'state'],
  ['컨텍스트', 'context'],
  ['프로바이더', 'provider'],
  ['리듀서', 'reducer'],
  ['디스패치', 'dispatch'],
  ['액션', 'action'],
  ['스토어', 'store'],
  ['셀렉터', 'selector'],
  ['스켈레톤', 'skeleton'],
  ['플레이스홀더', 'placeholder'],
  ['폼', 'form'],
  ['필드', 'field'],
  ['입력란', 'input field'],
  ['셀렉트', 'select'],
  ['콤보박스', 'combobox'],
  ['자동완성', 'autocomplete'],
  ['유효성 검사', 'validation'],
  ['필수', 'required'],
  ['아이디', 'ID'],
  ['비밀번호', 'password'],
  ['이메일', 'email'],
  ['닉네임', 'nickname'],
  ['프로필', 'profile'],
  ['대시보드', 'dashboard'],
  ['노티피케이션', 'notification'],
  ['알림', 'notification'],
  ['배너', 'banner'],
  ['공지', 'notice'],
  ['공지사항', 'notice'],
  ['컨텐츠', 'content'],
  ['콘텐츠', 'content'],
  ['미디어', 'media'],
  ['업로드', 'upload'],
  ['다운로드', 'download'],
  ['임포트', 'import'],
  ['익스포트', 'export'],
  ['내보내기', 'export'],
  ['가져오기', 'import/fetch'],
  ['불러오기', 'load'],
  ['스크롤', 'scroll'],
  ['커서', 'cursor'],
  ['포커스', 'focus'],
  ['블러', 'blur'],
  ['호버', 'hover'],
  ['드래그', 'drag'],
  ['드롭', 'drop'],
  ['리사이즈', 'resize'],
  ['토글', 'toggle'],
  ['확장', 'expand'],
  ['축소', 'collapse'],
  ['줌', 'zoom'],
  ['회전', 'rotate'],
  ['애니메이션', 'animation'],
  ['트랜지션', 'transition'],
  ['다크 모드', 'dark mode'],
  ['라이트 모드', 'light mode'],
  ['테마', 'theme'],
  ['로캘', 'locale'],
  ['번역', 'translation'],
  ['국제화', 'internationalization'],
  ['지역화', 'localization'],
  ['타임존', 'timezone'],
  ['날짜', 'date'],
  ['시간', 'time'],
  ['포맷', 'format'],
  ['파싱', 'parsing'],
  ['직렬화', 'serialization'],
  ['역직렬화', 'deserialization'],
  ['인코딩', 'encoding'],
  ['디코딩', 'decoding'],
  ['해시', 'hash'],
  ['암호화', 'encryption'],
  ['복호화', 'decryption'],
  ['압축', 'compression'],
  ['최적화', 'optimization'],
  ['성능', 'performance'],
  ['메모리', 'memory'],
  ['리소스', 'resource'],
  ['로그', 'log'],
  ['로깅', 'logging'],
  ['디버그', 'debug'],
  ['디버깅', 'debugging'],
  ['프로덕션', 'production'],
  ['개발', 'development'],
  ['테스트', 'test'],
  ['배포', 'deployment'],
  ['빌드', 'build'],
  ['컴파일', 'compile'],
  ['번들링', 'bundling'],
  ['채널', 'channel'],
  ['채팅', 'chat'],
  ['스레드', 'thread'],
  ['댓글', 'comment'],
  ['리액션', 'reaction'],
  ['좋아요', 'like'],
  ['팔로우', 'follow'],
  ['초대', 'invitation'],
  ['초대장', 'invitation'],
  ['수락', 'accept'],
  ['거절', 'reject'],
  ['차단', 'block'],
  ['신고', 'report'],
  ['멤버', 'member'],
  ['관리자', 'admin'],
  ['기여자', 'contributor'],
  ['게스트', 'guest'],
  ['소유자', 'owner'],
  ['역할', 'role'],
  ['접근', 'access'],
  ['제한', 'restriction'],
  ['허용', 'allow'],
  ['거부', 'deny'],
  ['잠금', 'lock'],
  ['해제', 'unlock'],
  ['감시', 'monitoring'],
  ['추적', 'tracking'],
  ['분석', 'analytics'],
  ['통계', 'statistics'],
  ['그래프', 'graph'],
  ['차트', 'chart'],
  ['대시보드', 'dashboard'],
  ['리포트', 'report'],
  ['요약', 'summary'],
  ['세부', 'detail'],
  ['상세', 'detail'],
  ['개요', 'overview'],
  ['미리보기', 'preview'],
  ['프리뷰', 'preview'],
  ['편집', 'edit'],
  ['읽기', 'read'],
  ['쓰기', 'write'],
  ['실행', 'execution'],
  ['중지', 'stop'],
  ['일시정지', 'pause'],
  ['재개', 'resume'],
  ['재시작', 'restart'],
  ['중단', 'abort'],
  ['재시도', 'retry'],
  ['복구', 'recovery'],
  ['백업', 'backup'],
  ['복원', 'restore'],
  ['초기값', 'initial value'],
  ['기본값', 'default value'],
  ['반환값', 'return value'],
  ['결과값', 'result value'],
  ['입력값', 'input value'],
  ['출력값', 'output value'],
  ['설정값', 'setting value'],
  ['제한값', 'limit value'],
  ['임계값', 'threshold'],
  ['문자열', 'string'],
  ['숫자', 'number'],
  ['정수', 'integer'],
  ['실수', 'float'],
  ['불리언', 'boolean'],
  ['배열', 'array'],
  ['객체', 'object'],
  ['함수', 'function'],
  ['변수', 'variable'],
  ['상수', 'constant'],
  ['타이머', 'timer'],
  ['인터벌', 'interval'],
  ['타임아웃', 'timeout'],
  ['지연', 'delay'],
  ['대기', 'wait'],
  ['폴링', 'polling'],
  ['루프', 'loop'],
  ['반복', 'repeat'],
  ['재귀', 'recursion'],
  ['콜스택', 'call stack'],
  ['이벤트루프', 'event loop'],
  ['비동기', 'async'],
  ['동기', 'sync'],
  ['병렬', 'parallel'],
  ['순차', 'sequential'],
  ['큐', 'queue'],
  ['스택', 'stack'],
  ['맵', 'map'],
  ['셋', 'set'],
  ['트리', 'tree'],
  ['그래프', 'graph'],
  ['노드', 'node'],
  ['엣지', 'edge'],
  ['루트', 'root'],
  ['리프', 'leaf'],
  ['부모', 'parent'],
  ['자식', 'child'],
  ['형제', 'sibling'],
  ['조상', 'ancestor'],
  ['후손', 'descendant'],
  ['깊이', 'depth'],
  ['너비', 'breadth'],
  ['탐색', 'traversal'],
  ['삽입', 'insertion'],
  ['수행', 'perform'],
  ['방식', 'method'],
  ['연산', 'operation'],
  ['처리', 'processing'],
  ['케이스', 'case'],
  ['시나리오', 'scenario'],
  ['워크플로우', 'workflow'],
  ['파이프라인', 'pipeline'],
  ['플로우', 'flow'],
  ['스텝', 'step'],
  ['단계', 'step'],
  ['프로세스', 'process'],
  ['작업', 'task'],
  ['잡', 'job'],
  ['이력', 'history'],
  ['기록', 'record'],
  ['로그', 'log'],
  ['감사', 'audit'],
  ['추적', 'trace'],
  ['스냅샷', 'snapshot'],
  ['보안', 'security'],
  ['인가', 'authorization'],
  ['인증', 'authentication'],
  ['토큰', 'token'],
  ['비밀키', 'secret key'],
  ['공개키', 'public key'],
  ['서명', 'signature'],
  ['검증', 'verification'],
  ['유효', 'valid'],
  ['만료', 'expiry'],
  ['갱신', 'renewal'],
  ['발급', 'issue'],
  ['폐기', 'revocation'],
  ['중복', 'duplicate'],
  ['고유', 'unique'],
  ['유일', 'unique'],
  ['필수', 'required'],
  ['선택', 'optional'],
  ['비어있', 'empty'],
  ['빈 값', 'empty value'],
  ['널', 'null'],
  ['언디파인드', 'undefined'],
  ['기능', 'feature'],
  ['모듈', 'module'],
  ['플러그인', 'plugin'],
  ['확장', 'extension'],
  ['훅', 'hook'],
  ['커스텀', 'custom'],
  ['기존', 'existing'],
  ['새로운', 'new'],
  ['이전', 'previous'],
  ['이후', 'after'],
  ['미리', 'pre'],
  ['뒤에', 'after'],
  ['전에', 'before'],
  ['중에', 'during'],
  ['사이에', 'between'],
  ['같이', 'together'],
  ['따로', 'separately'],
  ['직접', 'directly'],
  ['간접', 'indirectly'],
  ['명시적', 'explicit'],
  ['암시적', 'implicit'],
  ['가능한', 'possible'],
  ['불가능한', 'impossible'],
  ['필요한', 'necessary'],
  ['불필요한', 'unnecessary'],
  ['중요한', 'important'],
  ['주의', 'caution'],
  ['참고', 'note'],
  ['참조', 'reference'],
  ['예제', 'example'],
  ['예시', 'example'],
  ['샘플', 'sample'],
  ['기존의', 'existing'],
  ['새로운', 'new'],
  ['외부의', 'external'],
  ['내부의', 'internal'],
  ['공유', 'shared'],
  ['비공개', 'private'],
  ['공개', 'public'],
  ['게시', 'publish'],
  ['초안', 'draft'],
  ['승인', 'approval'],
  ['하단', 'bottom'],
  ['상단', 'top'],
  ['좌측', 'left'],
  ['우측', 'right'],
  ['상하', 'vertical'],
  ['좌우', 'horizontal'],
  ['가운데', 'center'],
  ['중앙', 'center'],
  ['무시', 'ignore'],
  ['건너뛰기', 'skip'],
  ['스킵', 'skip'],
  ['재활용', 'reuse'],
  ['재사용', 'reuse'],
  ['갱신하', 'refresh'],
  ['갱신된', 'refreshed'],
  ['한글', 'Korean'],
  ['영문', 'English'],
  ['중국어', 'Chinese'],
  ['한국어', 'Korean'],
  ['일본어', 'Japanese'],
  ['다국어', 'multi-language'],
  ['변환할', 'to convert'],
  ['지정된', 'specified'],
  // dateFormat.ts specific
  ['초단위', 'seconds-level'],
  ['방금 전', 'just now'],
  ['고정', 'fixed'],
  // commonly mixed patterns
  ['이면', 'if'],
  ['일 때', 'when'],
  ['에서', 'from/in'],
  ['으로', 'to/as'],
  ['로의', 'to'],
  ['에서의', 'from'],
  ['으로의', 'to'],
  ['와', 'and'],
  ['과', 'and'],
  ['의', 'of'],
  ['을', ''],
  ['를', ''],
  ['은', ''],
  ['는', ''],
  ['이', ''],
  ['가', ''],
  ['에', 'in'],
  ['도', 'also'],
  // Additional common phrases
  ['곗씠', 'data'],
  ['데이터', 'data'],
  ['컨트롤러', 'controller'],
  ['서비스', 'service'],
  ['라우터', 'router'],
  ['모델', 'model'],
  ['뷰', 'view'],
  ['템플릿', 'template'],
  ['템플릿을', 'template'],
  ['웹훅', 'webhook'],
  ['이벤트 리스너', 'event listener'],
  ['게시', 'publish'],
];

const dirs = [
  'packages/frontend/src',
  'packages/backend/src',
];

const excludeDirs = ['node_modules', 'dist', '.git', 'locales', 'contents'];
const extensions = ['.ts', '.tsx'];

function walk(dir) {
  const files = [];
  try {
    for (const f of fs.readdirSync(dir)) {
      if (excludeDirs.includes(f)) continue;
      const full = path.join(dir, f);
      const st = fs.statSync(full);
      if (st.isDirectory()) files.push(...walk(full));
      else if (extensions.some(ext => f.endsWith(ext))) files.push(full);
    }
  } catch(e) {}
  return files;
}

let totalFilesChanged = 0;
let totalLinesChanged = 0;

for (const dir of dirs) {
  const fullDir = path.join(base, dir);
  const files = walk(fullDir);
  
  for (const filePath of files) {
    let content = fs.readFileSync(filePath, 'utf-8');
    let changed = false;
    const lines = content.split('\n');
    
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      if (!koreanRegex.test(line)) continue;
      
      const trimmed = line.trim();
      const isComment = trimmed.startsWith('//') || trimmed.startsWith('*') || 
                       trimmed.startsWith('/*') || trimmed.includes('{/*');
      const commentIdx = line.indexOf('//');
      const isInlineComment = commentIdx >= 0 && koreanRegex.test(line.substring(commentIdx));
      const jsxCommentIdx = line.indexOf('{/*');
      const isJsxComment = jsxCommentIdx >= 0 && koreanRegex.test(line.substring(jsxCommentIdx));
      
      if (isComment || isInlineComment || isJsxComment) {
        let newLine = line;
        
        // Apply all translations, longest first to avoid partial replacement issues
        for (const [kr, en] of translations) {
          if (newLine.includes(kr)) {
            // Only replace in comment part of the line
            if (isInlineComment && !isComment) {
              // Replace only after //
              const before = newLine.substring(0, commentIdx);
              const after = newLine.substring(commentIdx);
              newLine = before + after.split(kr).join(en);
            } else {
              newLine = newLine.split(kr).join(en);
            }
          }
        }
        
        if (newLine !== line) {
          lines[i] = newLine;
          changed = true;
          totalLinesChanged++;
        }
      }
    }
    
    if (changed) {
      content = lines.join('\n');
      fs.writeFileSync(filePath, content, 'utf-8');
      const rel = path.relative(base, filePath).replace(/\\/g, '/');
      console.log('UPDATED: ' + rel);
      totalFilesChanged++;
    }
  }
}

console.log('\nTotal: ' + totalFilesChanged + ' files updated, ' + totalLinesChanged + ' lines changed');
