const fs = require('fs');
const path = require('path');
const dir = 'c:/work/uwo/gatrix/packages/frontend/src/services';
const files = fs.readdirSync(dir).filter(f => f.endsWith('.ts'));

const translations = {
  " 토큰 정보 디버깅": " Token information debugging",
  " 네트워크 오류 구분": " Network error classification",
  " ApiService.request()가 이미 response.data를 반환하므로": " ApiService.request() already returns response.data",
  " response는 백엔드에서 보낸 { success: true, data: {...} } 구조": " response is the { success: true, data: {...} } structure sent from backend",
  " 응답이 올바르지 않은 경우 기본값 반환": " Return default value if response is invalid",
  " API 응답 구조: { success: true, data: [...] }": " API response structure: { success: true, data: [...] }",
  " apiService는 이미 response.data를 반환하므로 response.data가 실제 데이터": " apiService already returns response.data, so response.data is the actual data",
  " 첨부파일이 있으면 FormData 사용, 없으면 JSON 사용": " Use FormData if attachments exist, otherwise use JSON",
  " 첨부파일이 없으면 JSON으로 전송": " Send as JSON if there are no attachments",
  " 토큰 만료 체크 및 갱신": " Check and refresh token expiration",
  " 백엔드를 통해 요청 (직접 라우트 사용)": " Request via backend (using direct route)",
  " 401 오류인 경우 토큰 갱신 후 재시도": " Retry after refreshing token on 401 error",
  " 토큰 유효성 확인 및 갱신": " Check and refresh token validity",
  " JWT 페이로드 디코딩하여 만료 시간 확인": " Decode JWT payload to check expiration time",
  " 토큰이 5분 이내에 만료되면 미리 갱신": " Proactively refresh token if it expires in less than 5 minutes",
  " 토큰 파싱 실패 시에도 갱신 시도": " Attempt to refresh even if token parsing fails",
  " 토큰 갱신": " Token refresh",
  " 사용자 초대": " Invite user",
  " 기존 JWT 토큰 사용 (별도 채팅 토큰 불필요)": " Use existing JWT token (no separate chat token needed)",
  " 의도적인 연결 해제가 아닌 경우에만 connection_lost 이벤트 발생": " Trigger connection_lost event only if not intentionally disconnected",
  " 서버 종료나 네트워크 문제로 인한 연결 끊김만 재연결 시도": " Only attempt reconnect for disconnects caused by server shutdown or network issues",
  " 토큰 갱신 시도": " Attempt to refresh token",
  " 새 토큰으로 재연결 시도": " Attempt to reconnect with new token",
  " 채팅 관련 이벤트들": " Chat related events",
  " 메시지 타입에 따라 적절한 이벤트로 변환": " Convert to appropriate event based on message type",
  " 기본 메시지 이벤트": " Default message event",
  " 백엔드에서 실제로 보내는 이벤트들만 처리": " Only handle events actually sent from backend",
  " 서버에서 보내는 타이핑 이벤트 (user_typing, user_stop_typing)": " Typing events sent from server (user_typing, user_stop_typing)",
  " 스레드 타이핑 이벤트": " Thread typing events",
  " 메시지 전송 완료 이벤트": " Message send complete event",
  " 새 메시지 이벤트 (BroadcastService에서)": " New message event (from BroadcastService)",
  " 초대 관련 이벤트들": " Invitation related events",
  " 메시지 리액션 관련 이벤트들": " Message reaction related events",
  " 사용자 상태 변경 이벤트": " User status change events",
  " 연결 관련 이벤트": " Connection related events",
  " 지수 백오프: 1초, 2초, 4초, 8초, 16초": " Exponential backoff: 1s, 2s, 4s, 8s, 16s",
  " 최대 30초": " Max 30 seconds",
  " 재연결 실패 시 다시 스케줄링": " Reschedule upon reconnect failure",
  " 사용자 상태 업데이트": " Update user status",
  " 사용 가능한 버전 목록 조회": " Get list of available versions",
  " 클라이언트 버전 목록 조회": " Get list of client versions",
  " 필터 조건 추가": " Add filter conditions",
  " 태그는 백엔드에서 배열 타입으로 기대하므로 반드시 배열 파라미터로 직렬화": " Tags are expected as an array type by backend, so must be serialized as array parameters",
  " 콤마 구분 문자열도 지원: \"1,2,3\" -> tags[]=1&tags[]=2&tags[]=3": " Also supports comma-separated string: \"1,2,3\" -> tags[]=1&tags[]=2&tags[]=3",
  " 배열인 경우 각 요소를 개별적으로 추가": " If array, add each element individually",
  " 혹시 다른 구조일 경우": " In case of different structure",
  " 응답이 올바르지 않거나 데이터가 없는 경우 기본값 반환": " Return default value if response is invalid or data is missing",
  " 클라이언트 버전 상세 조회": " Get client version details",
  " 클라이언트 버전 생성": " Create client version",
  " 정상 생성: { success: true, data: { ...created client version } }": " Normal creation: { success: true, data: { ...created client version } }",
  " 일부 서버는 생성 시 본문 없이 { success: true }만 반환할 수 있음": " Some servers may return only { success: true } without body upon creation",
  " 생성 직후 데이터 본문이 없는 서버 대응: 플랫폼/버전으로 재조회": " Handle servers missing data body immediately after creation: re-fetch by platform/version",
  " 클라이언트 버전 간편 생성": " Quick create client version",
  " 일부 서버는 본문 없이 { success: true }만 반환할 수 있음": " Some servers may return only { success: true } without body",
  " 클라이언트 버전 수정": " Update client version",
  " 정상 수정: { success: true, data: { ...updated client version } }": " Normal update: { success: true, data: { ...updated client version } }",
  " 클라이언트 버전 삭제": " Delete client version",
  " 202 응답은 CR 생성을 의미": " 202 response indicates CR creation",
  " 일괄 상태 변경": " Bulk update status",
  " 채널 목록 조회": " Get list of channels",
  " 메타데이터 조회 (플랫폼)": " Get metadata (platform)",
  " 클라이언트 버전 중복 검사": " Check for duplicate client version",
  " 정확히 일치하는 버전이 있는지 확인": " Check if exactly matching version exists",
  " 클라이언트 버전 내보내기 (CSV)": " Export client versions (CSV)",
  " 내보내기 전용 엔드포인트 사용": " Use endpoint dedicated for export",
  " 필터 추가": " Add filter",
  " 로컬 스토리지에서 페이지 크기 가져오기": " Get page size from local storage",
  " 로컬 스토리지에 페이지 크기 저장": " Save page size to local storage",
  " 로컬 스토리지에서 필터 가져오기": " Get filter from local storage",
  " 로컬 스토리지에 필터 저장": " Save filter to local storage",
  " 로컬 스토리지에서 정렬 설정 가져오기": " Get sorting options from local storage",
  " 로컬 스토리지에 정렬 설정 저장": " Save sorting options to local storage",
  " 클라이언트 버전 태그 조회": " Get client version tags",
  " 클라이언트 버전 태그 설정": " Set client version tag",
  " 응답 구조 확인 - 두 가지 경우 모두 처리": " Verify response structure - handle both cases",
  " 표준 응답 구조: { success: true, data: { worlds: [], total: 0 } }": " Standard response structure: { success: true, data: { worlds: [], total: 0 } }",
  " 직접 응답 구조: { worlds: [], total: 0 }": " Direct response structure: { worlds: [], total: 0 }",
  " apiService는 이미 response.data를 반환하므로": " apiService already returns response.data",
  " response는 백엔드에서 보낸 { success: true, data: {...} | null } 구조": " response is the { success: true, data: {...} | null } structure sent from backend",
  " 백엔드 응답 구조에 맞게 처리": " Process according to backend response structure",
  " 페이지네이션이 없는 경우 기본값 반환": " Return default value when pagination is missing",
  " 링크 미리보기 데이터를 가져옵니다": " Fetch link preview data",
  " 캐시에서 확인": " Check in cache",
  " 이미 요청 중인지 확인": " Check if already requesting",
  " 새로운 요청 생성": " Create new request",
  " 성공한 경우 캐시에 저장": " Save to cache if successful",
  " 요청 완료 후 pending 목록에서 제거": " Remove from pending list after request completes",
  " 실제 API 호출을 수행합니다": " Perform actual API call",
  " 캐시를 지웁니다": " Clear cache",
  " 특정 URL의 캐시를 제거합니다": " Remove cache for specific URL",
  " 캐시 크기를 반환합니다": " Return cache size",
  " URL이 링크 미리보기를 지원하는지 확인합니다": " Check if URL supports link preview",
  " HTTP/HTTPS만 지원": " Support only HTTP/HTTPS",
  " 이미지 파일은 제외": " Exclude image files",
  " 동영상 파일은 제외": " Exclude video files",
  " 문서 파일은 제외": " Exclude document files",
  " 텍스트에서 URL을 추출합니다": " Extract URL from text",
  " 여러 URL의 미리보기를 동시에 가져옵니다": " Fetch previews for multiple URLs concurrently",
  " 미리보기 가능한 URL만 필터링": " Filter only preview-supported URLs",
  " 동시에 모든 미리보기 요청": " Request all previews concurrently",
  " 발행 시간을 상대적 시간으로 변환합니다": " Convert published time to relative time",
  " 백워드 호환성: 배열이면 기존 형식, 객체면 새 형식": " Backward compatibility: existing format if array, new format if object",
  " 서버 응답 구조: { success: true, data: { items: ..., total: ... } }": " Server response structure: { success: true, data: { items: ..., total: ... } }",
  " data.data가 있으면 중첩된 구조": " Nested structure if data.data exists",
  " 서버 응답 구조: { success: true, data: created }": " Server response structure: { success: true, data: created }",
  " 백워드 호환성을 위한 다른 구조들": " Other structures for backward compatibility",
  " 서버 응답 구조: { success: true, data: updated }": " Server response structure: { success: true, data: updated }",
  " 태그 관련 메서드": " Tag related methods",
  " 모든 플랫폼의 기본값 조회": " Get default values of all platforms",
  " 특정 플랫폼의 기본값 조회": " Get default values of specific platform",
  " 특정 플랫폼의 기본값 설정": " Set default values of specific platform",
  " 모든 플랫폼의 기본값 일괄 설정": " Bulk set default values of all platforms",
  " 특정 플랫폼의 기본값 삭제": " Delete default values of specific platform",
  " 클라이언트 버전 데이터에 기본값 적용": " Apply default values to client version data",
  " 간편 추가용 플랫폼 데이터에 기본값 적용": " Apply default values to platform data for quick add",
  " Formatted and localized name (e.g., \"레드젬 600\")": " Formatted and localized name (e.g., \"Red Gem 600\")",
  " 서버 업타임 (초 단위)": " Server uptime (in seconds)",
  " 서버와 클라이언트 시간 차이 (ms)": " Time difference between server and client (ms)",
  " uptime 기준 시간 (timestamp)": " Uptime base time (timestamp)",
  " 서버 시간 조회 및 핑 계산": " Get server time and calculate ping",
  " 현재 계산된 서버 시간 반환 (실시간)": " Return currently calculated server time (real-time)",
  " 현재 서버 업타임 반환 (실시간)": " Return current server uptime (real-time)",
  " 초 단위": " In seconds",
  " 서버 시간 동기화 시작": " Start server time synchronization",
  " 최초에 한번은 즉시 호출": " Call immediately for the first time",
  " 일정주기마다 동기화": " Synchronize at regular intervals",
  " 서버 시간 동기화 중지": " Stop server time synchronization",
  " 서버 시간 업데이트 리스너 추가": " Add server time update listener",
  " 서버 시간 업데이트 리스너 제거": " Remove server time update listener",
  " 모든 리스너에게 알림": " Notify all listeners",
  " 현재 서버 시간 정보 반환": " Return current server time information",
  " 단일 언어로 번역": " Translate to single language",
  " 여러 언어로 동시 번역": " Translate to multiple languages concurrently",
  " 언어 감지": " Detect language",
  " 게임월드 점검 메시지 자동 번역": " Automatically translate game world maintenance messages",
  " 응답을 그대로 반환 (객체 형태 유지)": " Return response as is (keep object format)",
  " 번역 실패 시 원본 메시지를 모든 언어에 반환": " Return original message in all languages upon translation failure",
  " 언어 코드를 한국어 이름으로 변환": " Convert language code to Korean name",
  "      ko: '한국어',": "      ko: 'Korean',",
  "      en: '영어',": "      en: 'English',",
  "      zh: '중국어',": "      zh: 'Chinese',",
  "      'zh-cn': '중국어(간체)',": "      'zh-cn': 'Chinese (Simplified)',",
  "      ja: '일본어',": "      ja: 'Japanese',",
  "      auto: '자동 감지',": "      auto: 'Auto detect',",
  " 번역 가능한 언어 목록": " List of translatable languages",
  "      { code: 'ko', name: '한국어' },": "      { code: 'ko', name: 'Korean' },",
  "      { code: 'en', name: '영어' },": "      { code: 'en', name: 'English' },",
  "      { code: 'zh', name: '중국어' },": "      { code: 'zh', name: 'Chinese' },",
  " 관리자가 사용자 이메일을 강제 인증 처리": " Administrator forcibly verifies user email",
  " 사용자에게 이메일 인증 메일 재전송": " Resend email verification email to user",
  " 사용자 언어 설정 업데이트": " Update user language settings",
  " 캐시 방지를 위한 타임스탬프 추가 (개발 환경)": " Add timestamp to prevent caching (dev environment)",
  " response는 백엔드에서 보낸 { success: true, data: { whitelist: ... }, message: ... } 구조": " response is the { success: true, data: { whitelist: ... }, message: ... } structure sent from backend",
  " 태그 관련 메서드들": " Tag related methods"
};

files.forEach(f => {
  const filepath = path.join(dir, f);
  const content = fs.readFileSync(filepath, 'utf-8');
  if (/[가-힣]/.test(content)) {
    let newContent = content;
    const lines = content.split('\n');
    let modified = false;
    const newLines = lines.map(l => {
      const m = l.match(/^(.*?\/\/)(.*[가-힣].*)$/);
      if (m && translations[m[2]]) {
        modified = true;
        return m[1] + translations[m[2]];
      } else {
        const m2 = l.match(/^(.*?\*)(.*[가-힣].*)$/);
        if (m2 && !l.includes('*/') && translations[m2[2]]) {
          modified = true;
          return m2[1] + translations[m2[2]];
        }
      }
      return l;
    });
    if (modified) {
      fs.writeFileSync(filepath, newLines.join('\n'));
      console.log(`Updated ${f}`);
    }
  }
});
