import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Manually configured sidebar for better organization
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api/client-api',
      ],
    },
    {
      type: 'category',
      label: 'Backend',
      items: [
        'backend/cache-keys',
      ],
    },
    {
      type: 'category',
      label: 'Features',
      items: [
        'features/job-management',
        'features/game-worlds',
        'features/monitoring',
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      items: [
        'deployment/docker',
      ],
    },
    {
      type: 'category',
      label: 'Optimization',
      items: [
        'optimization/database',
        'optimization/caching',
      ],
    },
    {
      type: 'category',
      label: 'Tutorial',
      items: [
        {type: 'autogenerated', dirName: 'tutorial-basics'},
        {type: 'autogenerated', dirName: 'tutorial-extras'},
      ],
    },
  ],
};

export default sidebars;
