"""VariationProvider protocol – avoids circular FlagProxy ↔ FeaturesClient deps.

FlagProxy depends on this interface, FeaturesClient implements it.
"""
from __future__ import annotations

from typing import Any, Protocol

from gatrix.types import Variant, VariationResult


class VariationProvider(Protocol):
    """Protocol that FeaturesClient implements.
    FlagProxy delegates all variation logic here."""

    def is_enabled_internal(self, flag_name: str, force_realtime: bool = False) -> bool: ...
    def get_variant_internal(self, flag_name: str, force_realtime: bool = False) -> Variant: ...
    def variation_internal(self, flag_name: str, fallback_value: str, force_realtime: bool = False) -> str: ...
    def bool_variation_internal(self, flag_name: str, fallback_value: bool, force_realtime: bool = False) -> bool: ...
    def string_variation_internal(self, flag_name: str, fallback_value: str, force_realtime: bool = False) -> str: ...
    def int_variation_internal(self, flag_name: str, fallback_value: int, force_realtime: bool = False) -> int: ...
    def float_variation_internal(self, flag_name: str, fallback_value: float, force_realtime: bool = False) -> float: ...
    def json_variation_internal(self, flag_name: str, fallback_value: Any, force_realtime: bool = False) -> Any: ...

    def bool_variation_details_internal(self, flag_name: str, fallback_value: bool, force_realtime: bool = False) -> VariationResult: ...
    def string_variation_details_internal(self, flag_name: str, fallback_value: str, force_realtime: bool = False) -> VariationResult: ...
    def int_variation_details_internal(self, flag_name: str, fallback_value: int, force_realtime: bool = False) -> VariationResult: ...
    def float_variation_details_internal(self, flag_name: str, fallback_value: float, force_realtime: bool = False) -> VariationResult: ...
    def json_variation_details_internal(self, flag_name: str, fallback_value: Any, force_realtime: bool = False) -> VariationResult: ...

    def bool_variation_or_throw_internal(self, flag_name: str, force_realtime: bool = False) -> bool: ...
    def string_variation_or_throw_internal(self, flag_name: str, force_realtime: bool = False) -> str: ...
    def int_variation_or_throw_internal(self, flag_name: str, force_realtime: bool = False) -> int: ...
    def float_variation_or_throw_internal(self, flag_name: str, force_realtime: bool = False) -> float: ...
    def json_variation_or_throw_internal(self, flag_name: str, force_realtime: bool = False) -> Any: ...
