"""VariationProvider protocol – avoids circular FlagProxy ↔ FeaturesClient deps.

FlagProxy depends on this interface, FeaturesClient implements it.
"""
from __future__ import annotations

from typing import Any, Protocol

from gatrix.types import Variant, VariationResult


class VariationProvider(Protocol):
    """Protocol that FeaturesClient implements.
    FlagProxy delegates all variation logic here."""

    def is_enabled_internal(self, flag_name: str) -> bool: ...
    def get_variant_internal(self, flag_name: str) -> Variant: ...
    def variation_internal(self, flag_name: str, missing_value: str) -> str: ...
    def bool_variation_internal(self, flag_name: str, missing_value: bool) -> bool: ...
    def string_variation_internal(self, flag_name: str, missing_value: str) -> str: ...
    def int_variation_internal(self, flag_name: str, missing_value: int) -> int: ...
    def float_variation_internal(self, flag_name: str, missing_value: float) -> float: ...
    def json_variation_internal(self, flag_name: str, missing_value: Any) -> Any: ...

    def bool_variation_details_internal(self, flag_name: str, missing_value: bool) -> VariationResult: ...
    def string_variation_details_internal(self, flag_name: str, missing_value: str) -> VariationResult: ...
    def int_variation_details_internal(self, flag_name: str, missing_value: int) -> VariationResult: ...
    def float_variation_details_internal(self, flag_name: str, missing_value: float) -> VariationResult: ...
    def json_variation_details_internal(self, flag_name: str, missing_value: Any) -> VariationResult: ...

    def bool_variation_or_throw_internal(self, flag_name: str) -> bool: ...
    def string_variation_or_throw_internal(self, flag_name: str) -> str: ...
    def int_variation_or_throw_internal(self, flag_name: str) -> int: ...
    def float_variation_or_throw_internal(self, flag_name: str) -> float: ...
    def json_variation_or_throw_internal(self, flag_name: str) -> Any: ...
